/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"reflect"
)


type AgentRetrievalServiceAPI interface {

	/*
	AgentRetrievalServiceAttributeChangedFiles Method for AgentRetrievalServiceAttributeChangedFiles

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@param requirementId
	@return ApiAgentRetrievalServiceAttributeChangedFilesRequest
	*/
	AgentRetrievalServiceAttributeChangedFiles(ctx context.Context, productId string, requirementId string) ApiAgentRetrievalServiceAttributeChangedFilesRequest

	// AgentRetrievalServiceAttributeChangedFilesExecute executes the request
	//  @return AttributeChangedFilesResponse
	AgentRetrievalServiceAttributeChangedFilesExecute(r ApiAgentRetrievalServiceAttributeChangedFilesRequest) (*AttributeChangedFilesResponse, *http.Response, error)

	/*
	AgentRetrievalServiceDeclareRequirementEdgeIntent Method for AgentRetrievalServiceDeclareRequirementEdgeIntent

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@return ApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest
	*/
	AgentRetrievalServiceDeclareRequirementEdgeIntent(ctx context.Context, productId string) ApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest

	// AgentRetrievalServiceDeclareRequirementEdgeIntentExecute executes the request
	//  @return DeclareRequirementEdgeIntentResponse
	AgentRetrievalServiceDeclareRequirementEdgeIntentExecute(r ApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest) (*DeclareRequirementEdgeIntentResponse, *http.Response, error)

	/*
	AgentRetrievalServiceGetRequirementGraph Method for AgentRetrievalServiceGetRequirementGraph

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@return ApiAgentRetrievalServiceGetRequirementGraphRequest
	*/
	AgentRetrievalServiceGetRequirementGraph(ctx context.Context, productId string) ApiAgentRetrievalServiceGetRequirementGraphRequest

	// AgentRetrievalServiceGetRequirementGraphExecute executes the request
	//  @return GetRequirementGraphResponse
	AgentRetrievalServiceGetRequirementGraphExecute(r ApiAgentRetrievalServiceGetRequirementGraphRequest) (*GetRequirementGraphResponse, *http.Response, error)

	/*
	AgentRetrievalServiceGetRequirementTestContext Method for AgentRetrievalServiceGetRequirementTestContext

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@param requirementId
	@return ApiAgentRetrievalServiceGetRequirementTestContextRequest
	*/
	AgentRetrievalServiceGetRequirementTestContext(ctx context.Context, productId string, requirementId string) ApiAgentRetrievalServiceGetRequirementTestContextRequest

	// AgentRetrievalServiceGetRequirementTestContextExecute executes the request
	//  @return GetRequirementTestContextResponse
	AgentRetrievalServiceGetRequirementTestContextExecute(r ApiAgentRetrievalServiceGetRequirementTestContextRequest) (*GetRequirementTestContextResponse, *http.Response, error)

	/*
	AgentRetrievalServiceGraphCoverageGaps Method for AgentRetrievalServiceGraphCoverageGaps

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@return ApiAgentRetrievalServiceGraphCoverageGapsRequest
	*/
	AgentRetrievalServiceGraphCoverageGaps(ctx context.Context, productId string) ApiAgentRetrievalServiceGraphCoverageGapsRequest

	// AgentRetrievalServiceGraphCoverageGapsExecute executes the request
	//  @return GraphCoverageGapsResponse
	AgentRetrievalServiceGraphCoverageGapsExecute(r ApiAgentRetrievalServiceGraphCoverageGapsRequest) (*GraphCoverageGapsResponse, *http.Response, error)

	/*
	AgentRetrievalServiceListCoverageGaps Method for AgentRetrievalServiceListCoverageGaps

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@return ApiAgentRetrievalServiceListCoverageGapsRequest
	*/
	AgentRetrievalServiceListCoverageGaps(ctx context.Context, productId string) ApiAgentRetrievalServiceListCoverageGapsRequest

	// AgentRetrievalServiceListCoverageGapsExecute executes the request
	//  @return ListCoverageGapsResponse
	AgentRetrievalServiceListCoverageGapsExecute(r ApiAgentRetrievalServiceListCoverageGapsRequest) (*ListCoverageGapsResponse, *http.Response, error)

	/*
	AgentRetrievalServiceListRequirementAnchors Method for AgentRetrievalServiceListRequirementAnchors

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@return ApiAgentRetrievalServiceListRequirementAnchorsRequest
	*/
	AgentRetrievalServiceListRequirementAnchors(ctx context.Context, productId string) ApiAgentRetrievalServiceListRequirementAnchorsRequest

	// AgentRetrievalServiceListRequirementAnchorsExecute executes the request
	//  @return ListRequirementAnchorsResponse
	AgentRetrievalServiceListRequirementAnchorsExecute(r ApiAgentRetrievalServiceListRequirementAnchorsRequest) (*ListRequirementAnchorsResponse, *http.Response, error)

	/*
	AgentRetrievalServicePrepareTestGenerationContext Method for AgentRetrievalServicePrepareTestGenerationContext

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@return ApiAgentRetrievalServicePrepareTestGenerationContextRequest
	*/
	AgentRetrievalServicePrepareTestGenerationContext(ctx context.Context, productId string) ApiAgentRetrievalServicePrepareTestGenerationContextRequest

	// AgentRetrievalServicePrepareTestGenerationContextExecute executes the request
	//  @return PrepareTestGenerationContextResponse
	AgentRetrievalServicePrepareTestGenerationContextExecute(r ApiAgentRetrievalServicePrepareTestGenerationContextRequest) (*PrepareTestGenerationContextResponse, *http.Response, error)

	/*
	AgentRetrievalServiceRequirementImpact Method for AgentRetrievalServiceRequirementImpact

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@return ApiAgentRetrievalServiceRequirementImpactRequest
	*/
	AgentRetrievalServiceRequirementImpact(ctx context.Context, productId string) ApiAgentRetrievalServiceRequirementImpactRequest

	// AgentRetrievalServiceRequirementImpactExecute executes the request
	//  @return RequirementImpactResponse
	AgentRetrievalServiceRequirementImpactExecute(r ApiAgentRetrievalServiceRequirementImpactRequest) (*RequirementImpactResponse, *http.Response, error)

	/*
	AgentRetrievalServiceRequirementNeighbors Method for AgentRetrievalServiceRequirementNeighbors

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@param requirementId
	@return ApiAgentRetrievalServiceRequirementNeighborsRequest
	*/
	AgentRetrievalServiceRequirementNeighbors(ctx context.Context, productId string, requirementId string) ApiAgentRetrievalServiceRequirementNeighborsRequest

	// AgentRetrievalServiceRequirementNeighborsExecute executes the request
	//  @return RequirementNeighborsResponse
	AgentRetrievalServiceRequirementNeighborsExecute(r ApiAgentRetrievalServiceRequirementNeighborsRequest) (*RequirementNeighborsResponse, *http.Response, error)

	/*
	AgentRetrievalServiceResolveFeatureContext Method for AgentRetrievalServiceResolveFeatureContext

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@return ApiAgentRetrievalServiceResolveFeatureContextRequest
	*/
	AgentRetrievalServiceResolveFeatureContext(ctx context.Context, productId string) ApiAgentRetrievalServiceResolveFeatureContextRequest

	// AgentRetrievalServiceResolveFeatureContextExecute executes the request
	//  @return ResolveFeatureContextResponse
	AgentRetrievalServiceResolveFeatureContextExecute(r ApiAgentRetrievalServiceResolveFeatureContextRequest) (*ResolveFeatureContextResponse, *http.Response, error)

	/*
	AgentRetrievalServiceWriteRequirementEdge Method for AgentRetrievalServiceWriteRequirementEdge

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@return ApiAgentRetrievalServiceWriteRequirementEdgeRequest
	*/
	AgentRetrievalServiceWriteRequirementEdge(ctx context.Context, productId string) ApiAgentRetrievalServiceWriteRequirementEdgeRequest

	// AgentRetrievalServiceWriteRequirementEdgeExecute executes the request
	//  @return WriteRequirementEdgeResponse
	AgentRetrievalServiceWriteRequirementEdgeExecute(r ApiAgentRetrievalServiceWriteRequirementEdgeRequest) (*WriteRequirementEdgeResponse, *http.Response, error)
}

// AgentRetrievalServiceAPIService AgentRetrievalServiceAPI service
type AgentRetrievalServiceAPIService service

type ApiAgentRetrievalServiceAttributeChangedFilesRequest struct {
	ctx context.Context
	ApiService AgentRetrievalServiceAPI
	productId string
	requirementId string
	attributeChangedFilesBody *AttributeChangedFilesBody
}

func (r ApiAgentRetrievalServiceAttributeChangedFilesRequest) AttributeChangedFilesBody(attributeChangedFilesBody AttributeChangedFilesBody) ApiAgentRetrievalServiceAttributeChangedFilesRequest {
	r.attributeChangedFilesBody = &attributeChangedFilesBody
	return r
}

func (r ApiAgentRetrievalServiceAttributeChangedFilesRequest) Execute() (*AttributeChangedFilesResponse, *http.Response, error) {
	return r.ApiService.AgentRetrievalServiceAttributeChangedFilesExecute(r)
}

/*
AgentRetrievalServiceAttributeChangedFiles Method for AgentRetrievalServiceAttributeChangedFiles

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @param requirementId
 @return ApiAgentRetrievalServiceAttributeChangedFilesRequest
*/
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceAttributeChangedFiles(ctx context.Context, productId string, requirementId string) ApiAgentRetrievalServiceAttributeChangedFilesRequest {
	return ApiAgentRetrievalServiceAttributeChangedFilesRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
		requirementId: requirementId,
	}
}

// Execute executes the request
//  @return AttributeChangedFilesResponse
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceAttributeChangedFilesExecute(r ApiAgentRetrievalServiceAttributeChangedFilesRequest) (*AttributeChangedFilesResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AttributeChangedFilesResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentRetrievalServiceAPIService.AgentRetrievalServiceAttributeChangedFiles")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/requirements/{requirementId}:attribute-changed-files"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"requirementId"+"}", url.PathEscape(parameterValueToString(r.requirementId, "requirementId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.attributeChangedFilesBody == nil {
		return localVarReturnValue, nil, reportError("attributeChangedFilesBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.attributeChangedFilesBody
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest struct {
	ctx context.Context
	ApiService AgentRetrievalServiceAPI
	productId string
	declareRequirementEdgeIntentBody *DeclareRequirementEdgeIntentBody
}

func (r ApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest) DeclareRequirementEdgeIntentBody(declareRequirementEdgeIntentBody DeclareRequirementEdgeIntentBody) ApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest {
	r.declareRequirementEdgeIntentBody = &declareRequirementEdgeIntentBody
	return r
}

func (r ApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest) Execute() (*DeclareRequirementEdgeIntentResponse, *http.Response, error) {
	return r.ApiService.AgentRetrievalServiceDeclareRequirementEdgeIntentExecute(r)
}

/*
AgentRetrievalServiceDeclareRequirementEdgeIntent Method for AgentRetrievalServiceDeclareRequirementEdgeIntent

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @return ApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest
*/
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceDeclareRequirementEdgeIntent(ctx context.Context, productId string) ApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest {
	return ApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
	}
}

// Execute executes the request
//  @return DeclareRequirementEdgeIntentResponse
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceDeclareRequirementEdgeIntentExecute(r ApiAgentRetrievalServiceDeclareRequirementEdgeIntentRequest) (*DeclareRequirementEdgeIntentResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *DeclareRequirementEdgeIntentResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentRetrievalServiceAPIService.AgentRetrievalServiceDeclareRequirementEdgeIntent")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/requirement-edge-intents"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.declareRequirementEdgeIntentBody == nil {
		return localVarReturnValue, nil, reportError("declareRequirementEdgeIntentBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.declareRequirementEdgeIntentBody
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAgentRetrievalServiceGetRequirementGraphRequest struct {
	ctx context.Context
	ApiService AgentRetrievalServiceAPI
	productId string
}

func (r ApiAgentRetrievalServiceGetRequirementGraphRequest) Execute() (*GetRequirementGraphResponse, *http.Response, error) {
	return r.ApiService.AgentRetrievalServiceGetRequirementGraphExecute(r)
}

/*
AgentRetrievalServiceGetRequirementGraph Method for AgentRetrievalServiceGetRequirementGraph

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @return ApiAgentRetrievalServiceGetRequirementGraphRequest
*/
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceGetRequirementGraph(ctx context.Context, productId string) ApiAgentRetrievalServiceGetRequirementGraphRequest {
	return ApiAgentRetrievalServiceGetRequirementGraphRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
	}
}

// Execute executes the request
//  @return GetRequirementGraphResponse
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceGetRequirementGraphExecute(r ApiAgentRetrievalServiceGetRequirementGraphRequest) (*GetRequirementGraphResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetRequirementGraphResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentRetrievalServiceAPIService.AgentRetrievalServiceGetRequirementGraph")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/requirement-graph"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAgentRetrievalServiceGetRequirementTestContextRequest struct {
	ctx context.Context
	ApiService AgentRetrievalServiceAPI
	productId string
	requirementId string
	branch *string
	budget *int32
}

func (r ApiAgentRetrievalServiceGetRequirementTestContextRequest) Branch(branch string) ApiAgentRetrievalServiceGetRequirementTestContextRequest {
	r.branch = &branch
	return r
}

func (r ApiAgentRetrievalServiceGetRequirementTestContextRequest) Budget(budget int32) ApiAgentRetrievalServiceGetRequirementTestContextRequest {
	r.budget = &budget
	return r
}

func (r ApiAgentRetrievalServiceGetRequirementTestContextRequest) Execute() (*GetRequirementTestContextResponse, *http.Response, error) {
	return r.ApiService.AgentRetrievalServiceGetRequirementTestContextExecute(r)
}

/*
AgentRetrievalServiceGetRequirementTestContext Method for AgentRetrievalServiceGetRequirementTestContext

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @param requirementId
 @return ApiAgentRetrievalServiceGetRequirementTestContextRequest
*/
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceGetRequirementTestContext(ctx context.Context, productId string, requirementId string) ApiAgentRetrievalServiceGetRequirementTestContextRequest {
	return ApiAgentRetrievalServiceGetRequirementTestContextRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
		requirementId: requirementId,
	}
}

// Execute executes the request
//  @return GetRequirementTestContextResponse
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceGetRequirementTestContextExecute(r ApiAgentRetrievalServiceGetRequirementTestContextRequest) (*GetRequirementTestContextResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetRequirementTestContextResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentRetrievalServiceAPIService.AgentRetrievalServiceGetRequirementTestContext")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/requirements/{requirementId}/test-context"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"requirementId"+"}", url.PathEscape(parameterValueToString(r.requirementId, "requirementId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.branch != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "branch", r.branch, "form", "")
	}
	if r.budget != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "budget", r.budget, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAgentRetrievalServiceGraphCoverageGapsRequest struct {
	ctx context.Context
	ApiService AgentRetrievalServiceAPI
	productId string
	requirementIds *[]string
}

// requirement_ids is the set to check for coverage. Typically the result of RequirementImpact or RequirementNeighbors.
func (r ApiAgentRetrievalServiceGraphCoverageGapsRequest) RequirementIds(requirementIds []string) ApiAgentRetrievalServiceGraphCoverageGapsRequest {
	r.requirementIds = &requirementIds
	return r
}

func (r ApiAgentRetrievalServiceGraphCoverageGapsRequest) Execute() (*GraphCoverageGapsResponse, *http.Response, error) {
	return r.ApiService.AgentRetrievalServiceGraphCoverageGapsExecute(r)
}

/*
AgentRetrievalServiceGraphCoverageGaps Method for AgentRetrievalServiceGraphCoverageGaps

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @return ApiAgentRetrievalServiceGraphCoverageGapsRequest
*/
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceGraphCoverageGaps(ctx context.Context, productId string) ApiAgentRetrievalServiceGraphCoverageGapsRequest {
	return ApiAgentRetrievalServiceGraphCoverageGapsRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
	}
}

// Execute executes the request
//  @return GraphCoverageGapsResponse
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceGraphCoverageGapsExecute(r ApiAgentRetrievalServiceGraphCoverageGapsRequest) (*GraphCoverageGapsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GraphCoverageGapsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentRetrievalServiceAPIService.AgentRetrievalServiceGraphCoverageGaps")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/requirements/graph-coverage-gaps"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.requirementIds != nil {
		t := *r.requirementIds
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "requirementIds", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "requirementIds", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAgentRetrievalServiceListCoverageGapsRequest struct {
	ctx context.Context
	ApiService AgentRetrievalServiceAPI
	productId string
	branch *string
	coverageStatuses *[]string
	componentId *string
	query *string
	paginationPageSize *int32
	paginationPageToken *string
	rootRequirementId *string
}

func (r ApiAgentRetrievalServiceListCoverageGapsRequest) Branch(branch string) ApiAgentRetrievalServiceListCoverageGapsRequest {
	r.branch = &branch
	return r
}

func (r ApiAgentRetrievalServiceListCoverageGapsRequest) CoverageStatuses(coverageStatuses []string) ApiAgentRetrievalServiceListCoverageGapsRequest {
	r.coverageStatuses = &coverageStatuses
	return r
}

func (r ApiAgentRetrievalServiceListCoverageGapsRequest) ComponentId(componentId string) ApiAgentRetrievalServiceListCoverageGapsRequest {
	r.componentId = &componentId
	return r
}

func (r ApiAgentRetrievalServiceListCoverageGapsRequest) Query(query string) ApiAgentRetrievalServiceListCoverageGapsRequest {
	r.query = &query
	return r
}

func (r ApiAgentRetrievalServiceListCoverageGapsRequest) PaginationPageSize(paginationPageSize int32) ApiAgentRetrievalServiceListCoverageGapsRequest {
	r.paginationPageSize = &paginationPageSize
	return r
}

func (r ApiAgentRetrievalServiceListCoverageGapsRequest) PaginationPageToken(paginationPageToken string) ApiAgentRetrievalServiceListCoverageGapsRequest {
	r.paginationPageToken = &paginationPageToken
	return r
}

// scope gaps to a feature subtree (root + descendants)
func (r ApiAgentRetrievalServiceListCoverageGapsRequest) RootRequirementId(rootRequirementId string) ApiAgentRetrievalServiceListCoverageGapsRequest {
	r.rootRequirementId = &rootRequirementId
	return r
}

func (r ApiAgentRetrievalServiceListCoverageGapsRequest) Execute() (*ListCoverageGapsResponse, *http.Response, error) {
	return r.ApiService.AgentRetrievalServiceListCoverageGapsExecute(r)
}

/*
AgentRetrievalServiceListCoverageGaps Method for AgentRetrievalServiceListCoverageGaps

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @return ApiAgentRetrievalServiceListCoverageGapsRequest
*/
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceListCoverageGaps(ctx context.Context, productId string) ApiAgentRetrievalServiceListCoverageGapsRequest {
	return ApiAgentRetrievalServiceListCoverageGapsRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
	}
}

// Execute executes the request
//  @return ListCoverageGapsResponse
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceListCoverageGapsExecute(r ApiAgentRetrievalServiceListCoverageGapsRequest) (*ListCoverageGapsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListCoverageGapsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentRetrievalServiceAPIService.AgentRetrievalServiceListCoverageGaps")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/coverage-gaps"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.branch != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "branch", r.branch, "form", "")
	}
	if r.coverageStatuses != nil {
		t := *r.coverageStatuses
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "coverageStatuses", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "coverageStatuses", t, "form", "multi")
		}
	}
	if r.componentId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "componentId", r.componentId, "form", "")
	}
	if r.query != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "query", r.query, "form", "")
	}
	if r.paginationPageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pagination.pageSize", r.paginationPageSize, "form", "")
	}
	if r.paginationPageToken != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pagination.pageToken", r.paginationPageToken, "form", "")
	}
	if r.rootRequirementId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "rootRequirementId", r.rootRequirementId, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAgentRetrievalServiceListRequirementAnchorsRequest struct {
	ctx context.Context
	ApiService AgentRetrievalServiceAPI
	productId string
	branch *string
}

// empty &#x3D; main
func (r ApiAgentRetrievalServiceListRequirementAnchorsRequest) Branch(branch string) ApiAgentRetrievalServiceListRequirementAnchorsRequest {
	r.branch = &branch
	return r
}

func (r ApiAgentRetrievalServiceListRequirementAnchorsRequest) Execute() (*ListRequirementAnchorsResponse, *http.Response, error) {
	return r.ApiService.AgentRetrievalServiceListRequirementAnchorsExecute(r)
}

/*
AgentRetrievalServiceListRequirementAnchors Method for AgentRetrievalServiceListRequirementAnchors

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @return ApiAgentRetrievalServiceListRequirementAnchorsRequest
*/
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceListRequirementAnchors(ctx context.Context, productId string) ApiAgentRetrievalServiceListRequirementAnchorsRequest {
	return ApiAgentRetrievalServiceListRequirementAnchorsRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
	}
}

// Execute executes the request
//  @return ListRequirementAnchorsResponse
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceListRequirementAnchorsExecute(r ApiAgentRetrievalServiceListRequirementAnchorsRequest) (*ListRequirementAnchorsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListRequirementAnchorsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentRetrievalServiceAPIService.AgentRetrievalServiceListRequirementAnchors")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/requirement-anchors"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.branch != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "branch", r.branch, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAgentRetrievalServicePrepareTestGenerationContextRequest struct {
	ctx context.Context
	ApiService AgentRetrievalServiceAPI
	productId string
	prepareTestGenerationContextBody *PrepareTestGenerationContextBody
}

func (r ApiAgentRetrievalServicePrepareTestGenerationContextRequest) PrepareTestGenerationContextBody(prepareTestGenerationContextBody PrepareTestGenerationContextBody) ApiAgentRetrievalServicePrepareTestGenerationContextRequest {
	r.prepareTestGenerationContextBody = &prepareTestGenerationContextBody
	return r
}

func (r ApiAgentRetrievalServicePrepareTestGenerationContextRequest) Execute() (*PrepareTestGenerationContextResponse, *http.Response, error) {
	return r.ApiService.AgentRetrievalServicePrepareTestGenerationContextExecute(r)
}

/*
AgentRetrievalServicePrepareTestGenerationContext Method for AgentRetrievalServicePrepareTestGenerationContext

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @return ApiAgentRetrievalServicePrepareTestGenerationContextRequest
*/
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServicePrepareTestGenerationContext(ctx context.Context, productId string) ApiAgentRetrievalServicePrepareTestGenerationContextRequest {
	return ApiAgentRetrievalServicePrepareTestGenerationContextRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
	}
}

// Execute executes the request
//  @return PrepareTestGenerationContextResponse
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServicePrepareTestGenerationContextExecute(r ApiAgentRetrievalServicePrepareTestGenerationContextRequest) (*PrepareTestGenerationContextResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PrepareTestGenerationContextResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentRetrievalServiceAPIService.AgentRetrievalServicePrepareTestGenerationContext")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/test-generation-context:prepare"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.prepareTestGenerationContextBody == nil {
		return localVarReturnValue, nil, reportError("prepareTestGenerationContextBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.prepareTestGenerationContextBody
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAgentRetrievalServiceRequirementImpactRequest struct {
	ctx context.Context
	ApiService AgentRetrievalServiceAPI
	productId string
	repoPaths *[]string
	depth *int32
	edgeTypes *[]string
}

// repo_paths is the set of changed file paths (e.g. from a merged PR). The backend resolves these to seeded requirement IDs via requirement_sources.
func (r ApiAgentRetrievalServiceRequirementImpactRequest) RepoPaths(repoPaths []string) ApiAgentRetrievalServiceRequirementImpactRequest {
	r.repoPaths = &repoPaths
	return r
}

// depth controls how many hops the graph traversal expands beyond the seeds. Defaults to 3 on the server if &lt;&#x3D; 0.
func (r ApiAgentRetrievalServiceRequirementImpactRequest) Depth(depth int32) ApiAgentRetrievalServiceRequirementImpactRequest {
	r.depth = &depth
	return r
}

// edge_types filters which edge types to traverse. Empty &#x3D; all canonical types.
func (r ApiAgentRetrievalServiceRequirementImpactRequest) EdgeTypes(edgeTypes []string) ApiAgentRetrievalServiceRequirementImpactRequest {
	r.edgeTypes = &edgeTypes
	return r
}

func (r ApiAgentRetrievalServiceRequirementImpactRequest) Execute() (*RequirementImpactResponse, *http.Response, error) {
	return r.ApiService.AgentRetrievalServiceRequirementImpactExecute(r)
}

/*
AgentRetrievalServiceRequirementImpact Method for AgentRetrievalServiceRequirementImpact

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @return ApiAgentRetrievalServiceRequirementImpactRequest
*/
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceRequirementImpact(ctx context.Context, productId string) ApiAgentRetrievalServiceRequirementImpactRequest {
	return ApiAgentRetrievalServiceRequirementImpactRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
	}
}

// Execute executes the request
//  @return RequirementImpactResponse
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceRequirementImpactExecute(r ApiAgentRetrievalServiceRequirementImpactRequest) (*RequirementImpactResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *RequirementImpactResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentRetrievalServiceAPIService.AgentRetrievalServiceRequirementImpact")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/requirements/impact"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.repoPaths != nil {
		t := *r.repoPaths
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "repoPaths", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "repoPaths", t, "form", "multi")
		}
	}
	if r.depth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "depth", r.depth, "form", "")
	}
	if r.edgeTypes != nil {
		t := *r.edgeTypes
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "edgeTypes", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "edgeTypes", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAgentRetrievalServiceRequirementNeighborsRequest struct {
	ctx context.Context
	ApiService AgentRetrievalServiceAPI
	productId string
	requirementId string
	depth *int32
	edgeTypes *[]string
}

// depth controls how many hops to traverse (default 1 if &lt;&#x3D; 0).
func (r ApiAgentRetrievalServiceRequirementNeighborsRequest) Depth(depth int32) ApiAgentRetrievalServiceRequirementNeighborsRequest {
	r.depth = &depth
	return r
}

// edge_types filters which edge types to traverse. Empty &#x3D; all canonical types.
func (r ApiAgentRetrievalServiceRequirementNeighborsRequest) EdgeTypes(edgeTypes []string) ApiAgentRetrievalServiceRequirementNeighborsRequest {
	r.edgeTypes = &edgeTypes
	return r
}

func (r ApiAgentRetrievalServiceRequirementNeighborsRequest) Execute() (*RequirementNeighborsResponse, *http.Response, error) {
	return r.ApiService.AgentRetrievalServiceRequirementNeighborsExecute(r)
}

/*
AgentRetrievalServiceRequirementNeighbors Method for AgentRetrievalServiceRequirementNeighbors

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @param requirementId
 @return ApiAgentRetrievalServiceRequirementNeighborsRequest
*/
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceRequirementNeighbors(ctx context.Context, productId string, requirementId string) ApiAgentRetrievalServiceRequirementNeighborsRequest {
	return ApiAgentRetrievalServiceRequirementNeighborsRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
		requirementId: requirementId,
	}
}

// Execute executes the request
//  @return RequirementNeighborsResponse
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceRequirementNeighborsExecute(r ApiAgentRetrievalServiceRequirementNeighborsRequest) (*RequirementNeighborsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *RequirementNeighborsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentRetrievalServiceAPIService.AgentRetrievalServiceRequirementNeighbors")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/requirements/{requirementId}/neighbors"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"requirementId"+"}", url.PathEscape(parameterValueToString(r.requirementId, "requirementId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.depth != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "depth", r.depth, "form", "")
	}
	if r.edgeTypes != nil {
		t := *r.edgeTypes
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "edgeTypes", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "edgeTypes", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAgentRetrievalServiceResolveFeatureContextRequest struct {
	ctx context.Context
	ApiService AgentRetrievalServiceAPI
	productId string
	branch *string
	text *string
	repoPaths *[]string
	k *int32
}

// empty &#x3D; main
func (r ApiAgentRetrievalServiceResolveFeatureContextRequest) Branch(branch string) ApiAgentRetrievalServiceResolveFeatureContextRequest {
	r.branch = &branch
	return r
}

// text is the free-text coding objective to resolve into feature context.
func (r ApiAgentRetrievalServiceResolveFeatureContextRequest) Text(text string) ApiAgentRetrievalServiceResolveFeatureContextRequest {
	r.text = &text
	return r
}

// repo_paths are optional changed file paths that seed anchor retrieval.
func (r ApiAgentRetrievalServiceResolveFeatureContextRequest) RepoPaths(repoPaths []string) ApiAgentRetrievalServiceResolveFeatureContextRequest {
	r.repoPaths = &repoPaths
	return r
}

// k bounds each retrieval signal&#39;s breadth (server default when &lt;&#x3D; 0).
func (r ApiAgentRetrievalServiceResolveFeatureContextRequest) K(k int32) ApiAgentRetrievalServiceResolveFeatureContextRequest {
	r.k = &k
	return r
}

func (r ApiAgentRetrievalServiceResolveFeatureContextRequest) Execute() (*ResolveFeatureContextResponse, *http.Response, error) {
	return r.ApiService.AgentRetrievalServiceResolveFeatureContextExecute(r)
}

/*
AgentRetrievalServiceResolveFeatureContext Method for AgentRetrievalServiceResolveFeatureContext

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @return ApiAgentRetrievalServiceResolveFeatureContextRequest
*/
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceResolveFeatureContext(ctx context.Context, productId string) ApiAgentRetrievalServiceResolveFeatureContextRequest {
	return ApiAgentRetrievalServiceResolveFeatureContextRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
	}
}

// Execute executes the request
//  @return ResolveFeatureContextResponse
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceResolveFeatureContextExecute(r ApiAgentRetrievalServiceResolveFeatureContextRequest) (*ResolveFeatureContextResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ResolveFeatureContextResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentRetrievalServiceAPIService.AgentRetrievalServiceResolveFeatureContext")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/feature-context"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.branch != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "branch", r.branch, "form", "")
	}
	if r.text != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "text", r.text, "form", "")
	}
	if r.repoPaths != nil {
		t := *r.repoPaths
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "repoPaths", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "repoPaths", t, "form", "multi")
		}
	}
	if r.k != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "k", r.k, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAgentRetrievalServiceWriteRequirementEdgeRequest struct {
	ctx context.Context
	ApiService AgentRetrievalServiceAPI
	productId string
	writeRequirementEdgeBody *WriteRequirementEdgeBody
}

func (r ApiAgentRetrievalServiceWriteRequirementEdgeRequest) WriteRequirementEdgeBody(writeRequirementEdgeBody WriteRequirementEdgeBody) ApiAgentRetrievalServiceWriteRequirementEdgeRequest {
	r.writeRequirementEdgeBody = &writeRequirementEdgeBody
	return r
}

func (r ApiAgentRetrievalServiceWriteRequirementEdgeRequest) Execute() (*WriteRequirementEdgeResponse, *http.Response, error) {
	return r.ApiService.AgentRetrievalServiceWriteRequirementEdgeExecute(r)
}

/*
AgentRetrievalServiceWriteRequirementEdge Method for AgentRetrievalServiceWriteRequirementEdge

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @return ApiAgentRetrievalServiceWriteRequirementEdgeRequest
*/
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceWriteRequirementEdge(ctx context.Context, productId string) ApiAgentRetrievalServiceWriteRequirementEdgeRequest {
	return ApiAgentRetrievalServiceWriteRequirementEdgeRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
	}
}

// Execute executes the request
//  @return WriteRequirementEdgeResponse
func (a *AgentRetrievalServiceAPIService) AgentRetrievalServiceWriteRequirementEdgeExecute(r ApiAgentRetrievalServiceWriteRequirementEdgeRequest) (*WriteRequirementEdgeResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WriteRequirementEdgeResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentRetrievalServiceAPIService.AgentRetrievalServiceWriteRequirementEdge")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/requirement-edges"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.writeRequirementEdgeBody == nil {
		return localVarReturnValue, nil, reportError("writeRequirementEdgeBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.writeRequirementEdgeBody
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
