/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type ReleaseServiceAPI interface {

	/*
	ReleaseServiceCreateRelease Creates a release from an external source (CI/SDK).

	Idempotent upsert keyed on (product, version, environment): re-posting the
same version updates the existing release instead of duplicating it. The
environment is matched by slug and auto-created if unknown; released_at is
an RFC 3339 timestamp.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@return ApiReleaseServiceCreateReleaseRequest
	*/
	ReleaseServiceCreateRelease(ctx context.Context, productId string) ApiReleaseServiceCreateReleaseRequest

	// ReleaseServiceCreateReleaseExecute executes the request
	//  @return CreateReleaseResponse
	ReleaseServiceCreateReleaseExecute(r ApiReleaseServiceCreateReleaseRequest) (*CreateReleaseResponse, *http.Response, error)

	/*
	ReleaseServiceGetRelease Fetches one release by id.

	Returns the release with its version, environment, and metadata.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return ApiReleaseServiceGetReleaseRequest
	*/
	ReleaseServiceGetRelease(ctx context.Context, id string) ApiReleaseServiceGetReleaseRequest

	// ReleaseServiceGetReleaseExecute executes the request
	//  @return GetReleaseResponse
	ReleaseServiceGetReleaseExecute(r ApiReleaseServiceGetReleaseRequest) (*GetReleaseResponse, *http.Response, error)

	/*
	ReleaseServiceListReleases Lists a product's releases.

	Optionally filtered by environment slug; paginated via
pagination.page_size/page_token.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param productId
	@return ApiReleaseServiceListReleasesRequest
	*/
	ReleaseServiceListReleases(ctx context.Context, productId string) ApiReleaseServiceListReleasesRequest

	// ReleaseServiceListReleasesExecute executes the request
	//  @return ListReleasesResponse
	ReleaseServiceListReleasesExecute(r ApiReleaseServiceListReleasesRequest) (*ListReleasesResponse, *http.Response, error)
}

// ReleaseServiceAPIService ReleaseServiceAPI service
type ReleaseServiceAPIService service

type ApiReleaseServiceCreateReleaseRequest struct {
	ctx context.Context
	ApiService ReleaseServiceAPI
	productId string
	createReleaseBody *CreateReleaseBody
}

func (r ApiReleaseServiceCreateReleaseRequest) CreateReleaseBody(createReleaseBody CreateReleaseBody) ApiReleaseServiceCreateReleaseRequest {
	r.createReleaseBody = &createReleaseBody
	return r
}

func (r ApiReleaseServiceCreateReleaseRequest) Execute() (*CreateReleaseResponse, *http.Response, error) {
	return r.ApiService.ReleaseServiceCreateReleaseExecute(r)
}

/*
ReleaseServiceCreateRelease Creates a release from an external source (CI/SDK).

Idempotent upsert keyed on (product, version, environment): re-posting the
same version updates the existing release instead of duplicating it. The
environment is matched by slug and auto-created if unknown; released_at is
an RFC 3339 timestamp.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @return ApiReleaseServiceCreateReleaseRequest
*/
func (a *ReleaseServiceAPIService) ReleaseServiceCreateRelease(ctx context.Context, productId string) ApiReleaseServiceCreateReleaseRequest {
	return ApiReleaseServiceCreateReleaseRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
	}
}

// Execute executes the request
//  @return CreateReleaseResponse
func (a *ReleaseServiceAPIService) ReleaseServiceCreateReleaseExecute(r ApiReleaseServiceCreateReleaseRequest) (*CreateReleaseResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CreateReleaseResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ReleaseServiceAPIService.ReleaseServiceCreateRelease")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/releases"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createReleaseBody == nil {
		return localVarReturnValue, nil, reportError("createReleaseBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createReleaseBody
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiReleaseServiceGetReleaseRequest struct {
	ctx context.Context
	ApiService ReleaseServiceAPI
	id string
}

func (r ApiReleaseServiceGetReleaseRequest) Execute() (*GetReleaseResponse, *http.Response, error) {
	return r.ApiService.ReleaseServiceGetReleaseExecute(r)
}

/*
ReleaseServiceGetRelease Fetches one release by id.

Returns the release with its version, environment, and metadata.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return ApiReleaseServiceGetReleaseRequest
*/
func (a *ReleaseServiceAPIService) ReleaseServiceGetRelease(ctx context.Context, id string) ApiReleaseServiceGetReleaseRequest {
	return ApiReleaseServiceGetReleaseRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return GetReleaseResponse
func (a *ReleaseServiceAPIService) ReleaseServiceGetReleaseExecute(r ApiReleaseServiceGetReleaseRequest) (*GetReleaseResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *GetReleaseResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ReleaseServiceAPIService.ReleaseServiceGetRelease")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/releases/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiReleaseServiceListReleasesRequest struct {
	ctx context.Context
	ApiService ReleaseServiceAPI
	productId string
	environment *string
	paginationPageSize *int32
	paginationPageToken *string
}

// optional environment slug filter
func (r ApiReleaseServiceListReleasesRequest) Environment(environment string) ApiReleaseServiceListReleasesRequest {
	r.environment = &environment
	return r
}

func (r ApiReleaseServiceListReleasesRequest) PaginationPageSize(paginationPageSize int32) ApiReleaseServiceListReleasesRequest {
	r.paginationPageSize = &paginationPageSize
	return r
}

func (r ApiReleaseServiceListReleasesRequest) PaginationPageToken(paginationPageToken string) ApiReleaseServiceListReleasesRequest {
	r.paginationPageToken = &paginationPageToken
	return r
}

func (r ApiReleaseServiceListReleasesRequest) Execute() (*ListReleasesResponse, *http.Response, error) {
	return r.ApiService.ReleaseServiceListReleasesExecute(r)
}

/*
ReleaseServiceListReleases Lists a product's releases.

Optionally filtered by environment slug; paginated via
pagination.page_size/page_token.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param productId
 @return ApiReleaseServiceListReleasesRequest
*/
func (a *ReleaseServiceAPIService) ReleaseServiceListReleases(ctx context.Context, productId string) ApiReleaseServiceListReleasesRequest {
	return ApiReleaseServiceListReleasesRequest{
		ApiService: a,
		ctx: ctx,
		productId: productId,
	}
}

// Execute executes the request
//  @return ListReleasesResponse
func (a *ReleaseServiceAPIService) ReleaseServiceListReleasesExecute(r ApiReleaseServiceListReleasesRequest) (*ListReleasesResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListReleasesResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ReleaseServiceAPIService.ReleaseServiceListReleases")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/products/{productId}/releases"
	localVarPath = strings.Replace(localVarPath, "{"+"productId"+"}", url.PathEscape(parameterValueToString(r.productId, "productId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.environment != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "environment", r.environment, "form", "")
	}
	if r.paginationPageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pagination.pageSize", r.paginationPageSize, "form", "")
	}
	if r.paginationPageToken != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "pagination.pageToken", r.paginationPageToken, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["BearerAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v Status
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
