/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the GetIssueFixContextResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIssueFixContextResponse{}

// GetIssueFixContextResponse struct for GetIssueFixContextResponse
type GetIssueFixContextResponse struct {
	Context *IssueFixContext `json:"context,omitempty"`
}

// NewGetIssueFixContextResponse instantiates a new GetIssueFixContextResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIssueFixContextResponse() *GetIssueFixContextResponse {
	this := GetIssueFixContextResponse{}
	return &this
}

// NewGetIssueFixContextResponseWithDefaults instantiates a new GetIssueFixContextResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIssueFixContextResponseWithDefaults() *GetIssueFixContextResponse {
	this := GetIssueFixContextResponse{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *GetIssueFixContextResponse) GetContext() IssueFixContext {
	if o == nil || IsNil(o.Context) {
		var ret IssueFixContext
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssueFixContextResponse) GetContextOk() (*IssueFixContext, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *GetIssueFixContextResponse) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given IssueFixContext and assigns it to the Context field.
func (o *GetIssueFixContextResponse) SetContext(v IssueFixContext) {
	o.Context = &v
}

func (o GetIssueFixContextResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIssueFixContextResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	return toSerialize, nil
}

type NullableGetIssueFixContextResponse struct {
	value *GetIssueFixContextResponse
	isSet bool
}

func (v NullableGetIssueFixContextResponse) Get() *GetIssueFixContextResponse {
	return v.value
}

func (v *NullableGetIssueFixContextResponse) Set(val *GetIssueFixContextResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIssueFixContextResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIssueFixContextResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIssueFixContextResponse(val *GetIssueFixContextResponse) *NullableGetIssueFixContextResponse {
	return &NullableGetIssueFixContextResponse{value: val, isSet: true}
}

func (v NullableGetIssueFixContextResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIssueFixContextResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


