/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the Coverage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Coverage{}

// Coverage Coverage partitions a feature's slice into covered vs gap requirement ids using branch-effective coverage.
type Coverage struct {
	Covered []string `json:"covered,omitempty"`
	Gaps []string `json:"gaps,omitempty"`
}

// NewCoverage instantiates a new Coverage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoverage() *Coverage {
	this := Coverage{}
	return &this
}

// NewCoverageWithDefaults instantiates a new Coverage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoverageWithDefaults() *Coverage {
	this := Coverage{}
	return &this
}

// GetCovered returns the Covered field value if set, zero value otherwise.
func (o *Coverage) GetCovered() []string {
	if o == nil || IsNil(o.Covered) {
		var ret []string
		return ret
	}
	return o.Covered
}

// GetCoveredOk returns a tuple with the Covered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coverage) GetCoveredOk() ([]string, bool) {
	if o == nil || IsNil(o.Covered) {
		return nil, false
	}
	return o.Covered, true
}

// HasCovered returns a boolean if a field has been set.
func (o *Coverage) HasCovered() bool {
	if o != nil && !IsNil(o.Covered) {
		return true
	}

	return false
}

// SetCovered gets a reference to the given []string and assigns it to the Covered field.
func (o *Coverage) SetCovered(v []string) {
	o.Covered = v
}

// GetGaps returns the Gaps field value if set, zero value otherwise.
func (o *Coverage) GetGaps() []string {
	if o == nil || IsNil(o.Gaps) {
		var ret []string
		return ret
	}
	return o.Gaps
}

// GetGapsOk returns a tuple with the Gaps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coverage) GetGapsOk() ([]string, bool) {
	if o == nil || IsNil(o.Gaps) {
		return nil, false
	}
	return o.Gaps, true
}

// HasGaps returns a boolean if a field has been set.
func (o *Coverage) HasGaps() bool {
	if o != nil && !IsNil(o.Gaps) {
		return true
	}

	return false
}

// SetGaps gets a reference to the given []string and assigns it to the Gaps field.
func (o *Coverage) SetGaps(v []string) {
	o.Gaps = v
}

func (o Coverage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Coverage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Covered) {
		toSerialize["covered"] = o.Covered
	}
	if !IsNil(o.Gaps) {
		toSerialize["gaps"] = o.Gaps
	}
	return toSerialize, nil
}

type NullableCoverage struct {
	value *Coverage
	isSet bool
}

func (v NullableCoverage) Get() *Coverage {
	return v.value
}

func (v *NullableCoverage) Set(val *Coverage) {
	v.value = val
	v.isSet = true
}

func (v NullableCoverage) IsSet() bool {
	return v.isSet
}

func (v *NullableCoverage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoverage(val *Coverage) *NullableCoverage {
	return &NullableCoverage{value: val, isSet: true}
}

func (v NullableCoverage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoverage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


