/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
	"time"
)

// checks if the UserOnboardingState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserOnboardingState{}

// UserOnboardingState UserOnboardingState tracks a user's onboarding milestones as one-way timestamps (unset = not reached), plus the resumable creator-wizard position.
type UserOnboardingState struct {
	UserId *string `json:"userId,omitempty"`
	CliVerifiedAt *time.Time `json:"cliVerifiedAt,omitempty"`
	DismissedAt *time.Time `json:"dismissedAt,omitempty"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Current wizard screen; \"\" means the wizard was never started.
	WizardStep *string `json:"wizardStep,omitempty"`
	Answers *OnboardingAnswers `json:"answers,omitempty"`
}

// NewUserOnboardingState instantiates a new UserOnboardingState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserOnboardingState() *UserOnboardingState {
	this := UserOnboardingState{}
	return &this
}

// NewUserOnboardingStateWithDefaults instantiates a new UserOnboardingState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserOnboardingStateWithDefaults() *UserOnboardingState {
	this := UserOnboardingState{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *UserOnboardingState) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserOnboardingState) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *UserOnboardingState) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *UserOnboardingState) SetUserId(v string) {
	o.UserId = &v
}

// GetCliVerifiedAt returns the CliVerifiedAt field value if set, zero value otherwise.
func (o *UserOnboardingState) GetCliVerifiedAt() time.Time {
	if o == nil || IsNil(o.CliVerifiedAt) {
		var ret time.Time
		return ret
	}
	return *o.CliVerifiedAt
}

// GetCliVerifiedAtOk returns a tuple with the CliVerifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserOnboardingState) GetCliVerifiedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CliVerifiedAt) {
		return nil, false
	}
	return o.CliVerifiedAt, true
}

// HasCliVerifiedAt returns a boolean if a field has been set.
func (o *UserOnboardingState) HasCliVerifiedAt() bool {
	if o != nil && !IsNil(o.CliVerifiedAt) {
		return true
	}

	return false
}

// SetCliVerifiedAt gets a reference to the given time.Time and assigns it to the CliVerifiedAt field.
func (o *UserOnboardingState) SetCliVerifiedAt(v time.Time) {
	o.CliVerifiedAt = &v
}

// GetDismissedAt returns the DismissedAt field value if set, zero value otherwise.
func (o *UserOnboardingState) GetDismissedAt() time.Time {
	if o == nil || IsNil(o.DismissedAt) {
		var ret time.Time
		return ret
	}
	return *o.DismissedAt
}

// GetDismissedAtOk returns a tuple with the DismissedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserOnboardingState) GetDismissedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DismissedAt) {
		return nil, false
	}
	return o.DismissedAt, true
}

// HasDismissedAt returns a boolean if a field has been set.
func (o *UserOnboardingState) HasDismissedAt() bool {
	if o != nil && !IsNil(o.DismissedAt) {
		return true
	}

	return false
}

// SetDismissedAt gets a reference to the given time.Time and assigns it to the DismissedAt field.
func (o *UserOnboardingState) SetDismissedAt(v time.Time) {
	o.DismissedAt = &v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise.
func (o *UserOnboardingState) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserOnboardingState) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CompletedAt) {
		return nil, false
	}
	return o.CompletedAt, true
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *UserOnboardingState) HasCompletedAt() bool {
	if o != nil && !IsNil(o.CompletedAt) {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given time.Time and assigns it to the CompletedAt field.
func (o *UserOnboardingState) SetCompletedAt(v time.Time) {
	o.CompletedAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *UserOnboardingState) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserOnboardingState) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *UserOnboardingState) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *UserOnboardingState) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *UserOnboardingState) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserOnboardingState) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *UserOnboardingState) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *UserOnboardingState) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetWizardStep returns the WizardStep field value if set, zero value otherwise.
func (o *UserOnboardingState) GetWizardStep() string {
	if o == nil || IsNil(o.WizardStep) {
		var ret string
		return ret
	}
	return *o.WizardStep
}

// GetWizardStepOk returns a tuple with the WizardStep field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserOnboardingState) GetWizardStepOk() (*string, bool) {
	if o == nil || IsNil(o.WizardStep) {
		return nil, false
	}
	return o.WizardStep, true
}

// HasWizardStep returns a boolean if a field has been set.
func (o *UserOnboardingState) HasWizardStep() bool {
	if o != nil && !IsNil(o.WizardStep) {
		return true
	}

	return false
}

// SetWizardStep gets a reference to the given string and assigns it to the WizardStep field.
func (o *UserOnboardingState) SetWizardStep(v string) {
	o.WizardStep = &v
}

// GetAnswers returns the Answers field value if set, zero value otherwise.
func (o *UserOnboardingState) GetAnswers() OnboardingAnswers {
	if o == nil || IsNil(o.Answers) {
		var ret OnboardingAnswers
		return ret
	}
	return *o.Answers
}

// GetAnswersOk returns a tuple with the Answers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserOnboardingState) GetAnswersOk() (*OnboardingAnswers, bool) {
	if o == nil || IsNil(o.Answers) {
		return nil, false
	}
	return o.Answers, true
}

// HasAnswers returns a boolean if a field has been set.
func (o *UserOnboardingState) HasAnswers() bool {
	if o != nil && !IsNil(o.Answers) {
		return true
	}

	return false
}

// SetAnswers gets a reference to the given OnboardingAnswers and assigns it to the Answers field.
func (o *UserOnboardingState) SetAnswers(v OnboardingAnswers) {
	o.Answers = &v
}

func (o UserOnboardingState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserOnboardingState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.CliVerifiedAt) {
		toSerialize["cliVerifiedAt"] = o.CliVerifiedAt
	}
	if !IsNil(o.DismissedAt) {
		toSerialize["dismissedAt"] = o.DismissedAt
	}
	if !IsNil(o.CompletedAt) {
		toSerialize["completedAt"] = o.CompletedAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.WizardStep) {
		toSerialize["wizardStep"] = o.WizardStep
	}
	if !IsNil(o.Answers) {
		toSerialize["answers"] = o.Answers
	}
	return toSerialize, nil
}

type NullableUserOnboardingState struct {
	value *UserOnboardingState
	isSet bool
}

func (v NullableUserOnboardingState) Get() *UserOnboardingState {
	return v.value
}

func (v *NullableUserOnboardingState) Set(val *UserOnboardingState) {
	v.value = val
	v.isSet = true
}

func (v NullableUserOnboardingState) IsSet() bool {
	return v.isSet
}

func (v *NullableUserOnboardingState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserOnboardingState(val *UserOnboardingState) *NullableUserOnboardingState {
	return &NullableUserOnboardingState{value: val, isSet: true}
}

func (v NullableUserOnboardingState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserOnboardingState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


