/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the AttributedRequirementComponent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttributedRequirementComponent{}

// AttributedRequirementComponent AttributedRequirementComponent is one requirement newly attributed to a component from its own repo_file anchors this run.
type AttributedRequirementComponent struct {
	RequirementId *string `json:"requirementId,omitempty"`
	RequirementSeq *int32 `json:"requirementSeq,omitempty"`
	RequirementTitle *string `json:"requirementTitle,omitempty"`
	ComponentId *string `json:"componentId,omitempty"`
	ComponentName *string `json:"componentName,omitempty"`
}

// NewAttributedRequirementComponent instantiates a new AttributedRequirementComponent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttributedRequirementComponent() *AttributedRequirementComponent {
	this := AttributedRequirementComponent{}
	return &this
}

// NewAttributedRequirementComponentWithDefaults instantiates a new AttributedRequirementComponent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttributedRequirementComponentWithDefaults() *AttributedRequirementComponent {
	this := AttributedRequirementComponent{}
	return &this
}

// GetRequirementId returns the RequirementId field value if set, zero value otherwise.
func (o *AttributedRequirementComponent) GetRequirementId() string {
	if o == nil || IsNil(o.RequirementId) {
		var ret string
		return ret
	}
	return *o.RequirementId
}

// GetRequirementIdOk returns a tuple with the RequirementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributedRequirementComponent) GetRequirementIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequirementId) {
		return nil, false
	}
	return o.RequirementId, true
}

// HasRequirementId returns a boolean if a field has been set.
func (o *AttributedRequirementComponent) HasRequirementId() bool {
	if o != nil && !IsNil(o.RequirementId) {
		return true
	}

	return false
}

// SetRequirementId gets a reference to the given string and assigns it to the RequirementId field.
func (o *AttributedRequirementComponent) SetRequirementId(v string) {
	o.RequirementId = &v
}

// GetRequirementSeq returns the RequirementSeq field value if set, zero value otherwise.
func (o *AttributedRequirementComponent) GetRequirementSeq() int32 {
	if o == nil || IsNil(o.RequirementSeq) {
		var ret int32
		return ret
	}
	return *o.RequirementSeq
}

// GetRequirementSeqOk returns a tuple with the RequirementSeq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributedRequirementComponent) GetRequirementSeqOk() (*int32, bool) {
	if o == nil || IsNil(o.RequirementSeq) {
		return nil, false
	}
	return o.RequirementSeq, true
}

// HasRequirementSeq returns a boolean if a field has been set.
func (o *AttributedRequirementComponent) HasRequirementSeq() bool {
	if o != nil && !IsNil(o.RequirementSeq) {
		return true
	}

	return false
}

// SetRequirementSeq gets a reference to the given int32 and assigns it to the RequirementSeq field.
func (o *AttributedRequirementComponent) SetRequirementSeq(v int32) {
	o.RequirementSeq = &v
}

// GetRequirementTitle returns the RequirementTitle field value if set, zero value otherwise.
func (o *AttributedRequirementComponent) GetRequirementTitle() string {
	if o == nil || IsNil(o.RequirementTitle) {
		var ret string
		return ret
	}
	return *o.RequirementTitle
}

// GetRequirementTitleOk returns a tuple with the RequirementTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributedRequirementComponent) GetRequirementTitleOk() (*string, bool) {
	if o == nil || IsNil(o.RequirementTitle) {
		return nil, false
	}
	return o.RequirementTitle, true
}

// HasRequirementTitle returns a boolean if a field has been set.
func (o *AttributedRequirementComponent) HasRequirementTitle() bool {
	if o != nil && !IsNil(o.RequirementTitle) {
		return true
	}

	return false
}

// SetRequirementTitle gets a reference to the given string and assigns it to the RequirementTitle field.
func (o *AttributedRequirementComponent) SetRequirementTitle(v string) {
	o.RequirementTitle = &v
}

// GetComponentId returns the ComponentId field value if set, zero value otherwise.
func (o *AttributedRequirementComponent) GetComponentId() string {
	if o == nil || IsNil(o.ComponentId) {
		var ret string
		return ret
	}
	return *o.ComponentId
}

// GetComponentIdOk returns a tuple with the ComponentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributedRequirementComponent) GetComponentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ComponentId) {
		return nil, false
	}
	return o.ComponentId, true
}

// HasComponentId returns a boolean if a field has been set.
func (o *AttributedRequirementComponent) HasComponentId() bool {
	if o != nil && !IsNil(o.ComponentId) {
		return true
	}

	return false
}

// SetComponentId gets a reference to the given string and assigns it to the ComponentId field.
func (o *AttributedRequirementComponent) SetComponentId(v string) {
	o.ComponentId = &v
}

// GetComponentName returns the ComponentName field value if set, zero value otherwise.
func (o *AttributedRequirementComponent) GetComponentName() string {
	if o == nil || IsNil(o.ComponentName) {
		var ret string
		return ret
	}
	return *o.ComponentName
}

// GetComponentNameOk returns a tuple with the ComponentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributedRequirementComponent) GetComponentNameOk() (*string, bool) {
	if o == nil || IsNil(o.ComponentName) {
		return nil, false
	}
	return o.ComponentName, true
}

// HasComponentName returns a boolean if a field has been set.
func (o *AttributedRequirementComponent) HasComponentName() bool {
	if o != nil && !IsNil(o.ComponentName) {
		return true
	}

	return false
}

// SetComponentName gets a reference to the given string and assigns it to the ComponentName field.
func (o *AttributedRequirementComponent) SetComponentName(v string) {
	o.ComponentName = &v
}

func (o AttributedRequirementComponent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttributedRequirementComponent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequirementId) {
		toSerialize["requirementId"] = o.RequirementId
	}
	if !IsNil(o.RequirementSeq) {
		toSerialize["requirementSeq"] = o.RequirementSeq
	}
	if !IsNil(o.RequirementTitle) {
		toSerialize["requirementTitle"] = o.RequirementTitle
	}
	if !IsNil(o.ComponentId) {
		toSerialize["componentId"] = o.ComponentId
	}
	if !IsNil(o.ComponentName) {
		toSerialize["componentName"] = o.ComponentName
	}
	return toSerialize, nil
}

type NullableAttributedRequirementComponent struct {
	value *AttributedRequirementComponent
	isSet bool
}

func (v NullableAttributedRequirementComponent) Get() *AttributedRequirementComponent {
	return v.value
}

func (v *NullableAttributedRequirementComponent) Set(val *AttributedRequirementComponent) {
	v.value = val
	v.isSet = true
}

func (v NullableAttributedRequirementComponent) IsSet() bool {
	return v.isSet
}

func (v *NullableAttributedRequirementComponent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttributedRequirementComponent(val *AttributedRequirementComponent) *NullableAttributedRequirementComponent {
	return &NullableAttributedRequirementComponent{value: val, isSet: true}
}

func (v NullableAttributedRequirementComponent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttributedRequirementComponent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


