/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the RequirementAnchor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequirementAnchor{}

// RequirementAnchor RequirementAnchor is one (requirement, repo-relative path) code-anchor pair.
type RequirementAnchor struct {
	RequirementId *string `json:"requirementId,omitempty"`
	RepoPath *string `json:"repoPath,omitempty"`
}

// NewRequirementAnchor instantiates a new RequirementAnchor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequirementAnchor() *RequirementAnchor {
	this := RequirementAnchor{}
	return &this
}

// NewRequirementAnchorWithDefaults instantiates a new RequirementAnchor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequirementAnchorWithDefaults() *RequirementAnchor {
	this := RequirementAnchor{}
	return &this
}

// GetRequirementId returns the RequirementId field value if set, zero value otherwise.
func (o *RequirementAnchor) GetRequirementId() string {
	if o == nil || IsNil(o.RequirementId) {
		var ret string
		return ret
	}
	return *o.RequirementId
}

// GetRequirementIdOk returns a tuple with the RequirementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequirementAnchor) GetRequirementIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequirementId) {
		return nil, false
	}
	return o.RequirementId, true
}

// HasRequirementId returns a boolean if a field has been set.
func (o *RequirementAnchor) HasRequirementId() bool {
	if o != nil && !IsNil(o.RequirementId) {
		return true
	}

	return false
}

// SetRequirementId gets a reference to the given string and assigns it to the RequirementId field.
func (o *RequirementAnchor) SetRequirementId(v string) {
	o.RequirementId = &v
}

// GetRepoPath returns the RepoPath field value if set, zero value otherwise.
func (o *RequirementAnchor) GetRepoPath() string {
	if o == nil || IsNil(o.RepoPath) {
		var ret string
		return ret
	}
	return *o.RepoPath
}

// GetRepoPathOk returns a tuple with the RepoPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequirementAnchor) GetRepoPathOk() (*string, bool) {
	if o == nil || IsNil(o.RepoPath) {
		return nil, false
	}
	return o.RepoPath, true
}

// HasRepoPath returns a boolean if a field has been set.
func (o *RequirementAnchor) HasRepoPath() bool {
	if o != nil && !IsNil(o.RepoPath) {
		return true
	}

	return false
}

// SetRepoPath gets a reference to the given string and assigns it to the RepoPath field.
func (o *RequirementAnchor) SetRepoPath(v string) {
	o.RepoPath = &v
}

func (o RequirementAnchor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequirementAnchor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequirementId) {
		toSerialize["requirementId"] = o.RequirementId
	}
	if !IsNil(o.RepoPath) {
		toSerialize["repoPath"] = o.RepoPath
	}
	return toSerialize, nil
}

type NullableRequirementAnchor struct {
	value *RequirementAnchor
	isSet bool
}

func (v NullableRequirementAnchor) Get() *RequirementAnchor {
	return v.value
}

func (v *NullableRequirementAnchor) Set(val *RequirementAnchor) {
	v.value = val
	v.isSet = true
}

func (v NullableRequirementAnchor) IsSet() bool {
	return v.isSet
}

func (v *NullableRequirementAnchor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequirementAnchor(val *RequirementAnchor) *NullableRequirementAnchor {
	return &NullableRequirementAnchor{value: val, isSet: true}
}

func (v NullableRequirementAnchor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequirementAnchor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


