/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the ReportError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportError{}

// ReportError struct for ReportError
type ReportError struct {
	Index *int32 `json:"index,omitempty"`
	ResultId *string `json:"resultId,omitempty"`
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewReportError instantiates a new ReportError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportError() *ReportError {
	this := ReportError{}
	return &this
}

// NewReportErrorWithDefaults instantiates a new ReportError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportErrorWithDefaults() *ReportError {
	this := ReportError{}
	return &this
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *ReportError) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportError) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *ReportError) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *ReportError) SetIndex(v int32) {
	o.Index = &v
}

// GetResultId returns the ResultId field value if set, zero value otherwise.
func (o *ReportError) GetResultId() string {
	if o == nil || IsNil(o.ResultId) {
		var ret string
		return ret
	}
	return *o.ResultId
}

// GetResultIdOk returns a tuple with the ResultId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportError) GetResultIdOk() (*string, bool) {
	if o == nil || IsNil(o.ResultId) {
		return nil, false
	}
	return o.ResultId, true
}

// HasResultId returns a boolean if a field has been set.
func (o *ReportError) HasResultId() bool {
	if o != nil && !IsNil(o.ResultId) {
		return true
	}

	return false
}

// SetResultId gets a reference to the given string and assigns it to the ResultId field.
func (o *ReportError) SetResultId(v string) {
	o.ResultId = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ReportError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ReportError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ReportError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ReportError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReportError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ReportError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ReportError) SetMessage(v string) {
	o.Message = &v
}

func (o ReportError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	if !IsNil(o.ResultId) {
		toSerialize["resultId"] = o.ResultId
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableReportError struct {
	value *ReportError
	isSet bool
}

func (v NullableReportError) Get() *ReportError {
	return v.value
}

func (v *NullableReportError) Set(val *ReportError) {
	v.value = val
	v.isSet = true
}

func (v NullableReportError) IsSet() bool {
	return v.isSet
}

func (v *NullableReportError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportError(val *ReportError) *NullableReportError {
	return &NullableReportError{value: val, isSet: true}
}

func (v NullableReportError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


