/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the ReviewBranchLinkProposalsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewBranchLinkProposalsResponse{}

// ReviewBranchLinkProposalsResponse struct for ReviewBranchLinkProposalsResponse
type ReviewBranchLinkProposalsResponse struct {
	Proposals []BranchRequirementLinkProposal `json:"proposals,omitempty"`
}

// NewReviewBranchLinkProposalsResponse instantiates a new ReviewBranchLinkProposalsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewBranchLinkProposalsResponse() *ReviewBranchLinkProposalsResponse {
	this := ReviewBranchLinkProposalsResponse{}
	return &this
}

// NewReviewBranchLinkProposalsResponseWithDefaults instantiates a new ReviewBranchLinkProposalsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewBranchLinkProposalsResponseWithDefaults() *ReviewBranchLinkProposalsResponse {
	this := ReviewBranchLinkProposalsResponse{}
	return &this
}

// GetProposals returns the Proposals field value if set, zero value otherwise.
func (o *ReviewBranchLinkProposalsResponse) GetProposals() []BranchRequirementLinkProposal {
	if o == nil || IsNil(o.Proposals) {
		var ret []BranchRequirementLinkProposal
		return ret
	}
	return o.Proposals
}

// GetProposalsOk returns a tuple with the Proposals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReviewBranchLinkProposalsResponse) GetProposalsOk() ([]BranchRequirementLinkProposal, bool) {
	if o == nil || IsNil(o.Proposals) {
		return nil, false
	}
	return o.Proposals, true
}

// HasProposals returns a boolean if a field has been set.
func (o *ReviewBranchLinkProposalsResponse) HasProposals() bool {
	if o != nil && !IsNil(o.Proposals) {
		return true
	}

	return false
}

// SetProposals gets a reference to the given []BranchRequirementLinkProposal and assigns it to the Proposals field.
func (o *ReviewBranchLinkProposalsResponse) SetProposals(v []BranchRequirementLinkProposal) {
	o.Proposals = v
}

func (o ReviewBranchLinkProposalsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewBranchLinkProposalsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Proposals) {
		toSerialize["proposals"] = o.Proposals
	}
	return toSerialize, nil
}

type NullableReviewBranchLinkProposalsResponse struct {
	value *ReviewBranchLinkProposalsResponse
	isSet bool
}

func (v NullableReviewBranchLinkProposalsResponse) Get() *ReviewBranchLinkProposalsResponse {
	return v.value
}

func (v *NullableReviewBranchLinkProposalsResponse) Set(val *ReviewBranchLinkProposalsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewBranchLinkProposalsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewBranchLinkProposalsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewBranchLinkProposalsResponse(val *ReviewBranchLinkProposalsResponse) *NullableReviewBranchLinkProposalsResponse {
	return &NullableReviewBranchLinkProposalsResponse{value: val, isSet: true}
}

func (v NullableReviewBranchLinkProposalsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewBranchLinkProposalsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


