/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the StartAgentRunResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartAgentRunResponse{}

// StartAgentRunResponse struct for StartAgentRunResponse
type StartAgentRunResponse struct {
	Run *AgentRun `json:"run,omitempty"`
}

// NewStartAgentRunResponse instantiates a new StartAgentRunResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartAgentRunResponse() *StartAgentRunResponse {
	this := StartAgentRunResponse{}
	return &this
}

// NewStartAgentRunResponseWithDefaults instantiates a new StartAgentRunResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartAgentRunResponseWithDefaults() *StartAgentRunResponse {
	this := StartAgentRunResponse{}
	return &this
}

// GetRun returns the Run field value if set, zero value otherwise.
func (o *StartAgentRunResponse) GetRun() AgentRun {
	if o == nil || IsNil(o.Run) {
		var ret AgentRun
		return ret
	}
	return *o.Run
}

// GetRunOk returns a tuple with the Run field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartAgentRunResponse) GetRunOk() (*AgentRun, bool) {
	if o == nil || IsNil(o.Run) {
		return nil, false
	}
	return o.Run, true
}

// HasRun returns a boolean if a field has been set.
func (o *StartAgentRunResponse) HasRun() bool {
	if o != nil && !IsNil(o.Run) {
		return true
	}

	return false
}

// SetRun gets a reference to the given AgentRun and assigns it to the Run field.
func (o *StartAgentRunResponse) SetRun(v AgentRun) {
	o.Run = &v
}

func (o StartAgentRunResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartAgentRunResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Run) {
		toSerialize["run"] = o.Run
	}
	return toSerialize, nil
}

type NullableStartAgentRunResponse struct {
	value *StartAgentRunResponse
	isSet bool
}

func (v NullableStartAgentRunResponse) Get() *StartAgentRunResponse {
	return v.value
}

func (v *NullableStartAgentRunResponse) Set(val *StartAgentRunResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStartAgentRunResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStartAgentRunResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartAgentRunResponse(val *StartAgentRunResponse) *NullableStartAgentRunResponse {
	return &NullableStartAgentRunResponse{value: val, isSet: true}
}

func (v NullableStartAgentRunResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartAgentRunResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


