/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the RequirementNeighborsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequirementNeighborsResponse{}

// RequirementNeighborsResponse struct for RequirementNeighborsResponse
type RequirementNeighborsResponse struct {
	NeighborIds []string `json:"neighborIds,omitempty"`
}

// NewRequirementNeighborsResponse instantiates a new RequirementNeighborsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequirementNeighborsResponse() *RequirementNeighborsResponse {
	this := RequirementNeighborsResponse{}
	return &this
}

// NewRequirementNeighborsResponseWithDefaults instantiates a new RequirementNeighborsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequirementNeighborsResponseWithDefaults() *RequirementNeighborsResponse {
	this := RequirementNeighborsResponse{}
	return &this
}

// GetNeighborIds returns the NeighborIds field value if set, zero value otherwise.
func (o *RequirementNeighborsResponse) GetNeighborIds() []string {
	if o == nil || IsNil(o.NeighborIds) {
		var ret []string
		return ret
	}
	return o.NeighborIds
}

// GetNeighborIdsOk returns a tuple with the NeighborIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequirementNeighborsResponse) GetNeighborIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.NeighborIds) {
		return nil, false
	}
	return o.NeighborIds, true
}

// HasNeighborIds returns a boolean if a field has been set.
func (o *RequirementNeighborsResponse) HasNeighborIds() bool {
	if o != nil && !IsNil(o.NeighborIds) {
		return true
	}

	return false
}

// SetNeighborIds gets a reference to the given []string and assigns it to the NeighborIds field.
func (o *RequirementNeighborsResponse) SetNeighborIds(v []string) {
	o.NeighborIds = v
}

func (o RequirementNeighborsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequirementNeighborsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NeighborIds) {
		toSerialize["neighborIds"] = o.NeighborIds
	}
	return toSerialize, nil
}

type NullableRequirementNeighborsResponse struct {
	value *RequirementNeighborsResponse
	isSet bool
}

func (v NullableRequirementNeighborsResponse) Get() *RequirementNeighborsResponse {
	return v.value
}

func (v *NullableRequirementNeighborsResponse) Set(val *RequirementNeighborsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRequirementNeighborsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRequirementNeighborsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequirementNeighborsResponse(val *RequirementNeighborsResponse) *NullableRequirementNeighborsResponse {
	return &NullableRequirementNeighborsResponse{value: val, isSet: true}
}

func (v NullableRequirementNeighborsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequirementNeighborsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


