/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
	"fmt"
)

// VerdictScope the model 'VerdictScope'
type VerdictScope string

// List of VerdictScope
const (
	VERDICT_SCOPE_UNSPECIFIED VerdictScope = "VERDICT_SCOPE_UNSPECIFIED"
	VERDICT_SCOPE_RELEASE VerdictScope = "VERDICT_SCOPE_RELEASE"
	VERDICT_SCOPE_BRANCH VerdictScope = "VERDICT_SCOPE_BRANCH"
	VERDICT_SCOPE_MAIN VerdictScope = "VERDICT_SCOPE_MAIN"
)

// All allowed values of VerdictScope enum
var AllowedVerdictScopeEnumValues = []VerdictScope{
	"VERDICT_SCOPE_UNSPECIFIED",
	"VERDICT_SCOPE_RELEASE",
	"VERDICT_SCOPE_BRANCH",
	"VERDICT_SCOPE_MAIN",
}

func (v *VerdictScope) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VerdictScope(value)
	for _, existing := range AllowedVerdictScopeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VerdictScope", value)
}

// NewVerdictScopeFromValue returns a pointer to a valid VerdictScope
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVerdictScopeFromValue(v string) (*VerdictScope, error) {
	ev := VerdictScope(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for VerdictScope: valid values are %v", v, AllowedVerdictScopeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VerdictScope) IsValid() bool {
	for _, existing := range AllowedVerdictScopeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to VerdictScope value
func (v VerdictScope) Ptr() *VerdictScope {
	return &v
}

type NullableVerdictScope struct {
	value *VerdictScope
	isSet bool
}

func (v NullableVerdictScope) Get() *VerdictScope {
	return v.value
}

func (v *NullableVerdictScope) Set(val *VerdictScope) {
	v.value = val
	v.isSet = true
}

func (v NullableVerdictScope) IsSet() bool {
	return v.isSet
}

func (v *NullableVerdictScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerdictScope(val *VerdictScope) *NullableVerdictScope {
	return &NullableVerdictScope{value: val, isSet: true}
}

func (v NullableVerdictScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerdictScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

