/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the TouchedNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TouchedNode{}

// TouchedNode TouchedNode is one node of a feature's relevance slice (a seed, an ancestor on the seed->root path, or a co_anchored neighbor). resources are its branch-effective repo_file anchor paths.
type TouchedNode struct {
	Id *string `json:"id,omitempty"`
	SeqNum *int32 `json:"seqNum,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Resources []string `json:"resources,omitempty"`
	// repository is the canonical repo id of this node's component (shift-left v3), or \"\" when unscoped. Lets the CLI verdict compare changed files vs resources per-repo (avoids cross-repo path collisions). resources are repo-relative.
	Repository *string `json:"repository,omitempty"`
}

// NewTouchedNode instantiates a new TouchedNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTouchedNode() *TouchedNode {
	this := TouchedNode{}
	return &this
}

// NewTouchedNodeWithDefaults instantiates a new TouchedNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTouchedNodeWithDefaults() *TouchedNode {
	this := TouchedNode{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TouchedNode) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TouchedNode) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TouchedNode) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TouchedNode) SetId(v string) {
	o.Id = &v
}

// GetSeqNum returns the SeqNum field value if set, zero value otherwise.
func (o *TouchedNode) GetSeqNum() int32 {
	if o == nil || IsNil(o.SeqNum) {
		var ret int32
		return ret
	}
	return *o.SeqNum
}

// GetSeqNumOk returns a tuple with the SeqNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TouchedNode) GetSeqNumOk() (*int32, bool) {
	if o == nil || IsNil(o.SeqNum) {
		return nil, false
	}
	return o.SeqNum, true
}

// HasSeqNum returns a boolean if a field has been set.
func (o *TouchedNode) HasSeqNum() bool {
	if o != nil && !IsNil(o.SeqNum) {
		return true
	}

	return false
}

// SetSeqNum gets a reference to the given int32 and assigns it to the SeqNum field.
func (o *TouchedNode) SetSeqNum(v int32) {
	o.SeqNum = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *TouchedNode) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TouchedNode) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *TouchedNode) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *TouchedNode) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TouchedNode) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TouchedNode) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TouchedNode) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TouchedNode) SetDescription(v string) {
	o.Description = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *TouchedNode) GetResources() []string {
	if o == nil || IsNil(o.Resources) {
		var ret []string
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TouchedNode) GetResourcesOk() ([]string, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *TouchedNode) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given []string and assigns it to the Resources field.
func (o *TouchedNode) SetResources(v []string) {
	o.Resources = v
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *TouchedNode) GetRepository() string {
	if o == nil || IsNil(o.Repository) {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TouchedNode) GetRepositoryOk() (*string, bool) {
	if o == nil || IsNil(o.Repository) {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *TouchedNode) HasRepository() bool {
	if o != nil && !IsNil(o.Repository) {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *TouchedNode) SetRepository(v string) {
	o.Repository = &v
}

func (o TouchedNode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TouchedNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SeqNum) {
		toSerialize["seqNum"] = o.SeqNum
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if !IsNil(o.Repository) {
		toSerialize["repository"] = o.Repository
	}
	return toSerialize, nil
}

type NullableTouchedNode struct {
	value *TouchedNode
	isSet bool
}

func (v NullableTouchedNode) Get() *TouchedNode {
	return v.value
}

func (v *NullableTouchedNode) Set(val *TouchedNode) {
	v.value = val
	v.isSet = true
}

func (v NullableTouchedNode) IsSet() bool {
	return v.isSet
}

func (v *NullableTouchedNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTouchedNode(val *TouchedNode) *NullableTouchedNode {
	return &NullableTouchedNode{value: val, isSet: true}
}

func (v NullableTouchedNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTouchedNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


