/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the ListComponentsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListComponentsResponse{}

// ListComponentsResponse struct for ListComponentsResponse
type ListComponentsResponse struct {
	Components []Component `json:"components,omitempty"`
	Pagination *PaginationResponse `json:"pagination,omitempty"`
}

// NewListComponentsResponse instantiates a new ListComponentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListComponentsResponse() *ListComponentsResponse {
	this := ListComponentsResponse{}
	return &this
}

// NewListComponentsResponseWithDefaults instantiates a new ListComponentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListComponentsResponseWithDefaults() *ListComponentsResponse {
	this := ListComponentsResponse{}
	return &this
}

// GetComponents returns the Components field value if set, zero value otherwise.
func (o *ListComponentsResponse) GetComponents() []Component {
	if o == nil || IsNil(o.Components) {
		var ret []Component
		return ret
	}
	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListComponentsResponse) GetComponentsOk() ([]Component, bool) {
	if o == nil || IsNil(o.Components) {
		return nil, false
	}
	return o.Components, true
}

// HasComponents returns a boolean if a field has been set.
func (o *ListComponentsResponse) HasComponents() bool {
	if o != nil && !IsNil(o.Components) {
		return true
	}

	return false
}

// SetComponents gets a reference to the given []Component and assigns it to the Components field.
func (o *ListComponentsResponse) SetComponents(v []Component) {
	o.Components = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ListComponentsResponse) GetPagination() PaginationResponse {
	if o == nil || IsNil(o.Pagination) {
		var ret PaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListComponentsResponse) GetPaginationOk() (*PaginationResponse, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ListComponentsResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationResponse and assigns it to the Pagination field.
func (o *ListComponentsResponse) SetPagination(v PaginationResponse) {
	o.Pagination = &v
}

func (o ListComponentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListComponentsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Components) {
		toSerialize["components"] = o.Components
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableListComponentsResponse struct {
	value *ListComponentsResponse
	isSet bool
}

func (v NullableListComponentsResponse) Get() *ListComponentsResponse {
	return v.value
}

func (v *NullableListComponentsResponse) Set(val *ListComponentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListComponentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListComponentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListComponentsResponse(val *ListComponentsResponse) *NullableListComponentsResponse {
	return &NullableListComponentsResponse{value: val, isSet: true}
}

func (v NullableListComponentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListComponentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


