/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the ConfirmSourceMapUploadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfirmSourceMapUploadResponse{}

// ConfirmSourceMapUploadResponse struct for ConfirmSourceMapUploadResponse
type ConfirmSourceMapUploadResponse struct {
	SourceMap *SourceMap `json:"sourceMap,omitempty"`
}

// NewConfirmSourceMapUploadResponse instantiates a new ConfirmSourceMapUploadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfirmSourceMapUploadResponse() *ConfirmSourceMapUploadResponse {
	this := ConfirmSourceMapUploadResponse{}
	return &this
}

// NewConfirmSourceMapUploadResponseWithDefaults instantiates a new ConfirmSourceMapUploadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfirmSourceMapUploadResponseWithDefaults() *ConfirmSourceMapUploadResponse {
	this := ConfirmSourceMapUploadResponse{}
	return &this
}

// GetSourceMap returns the SourceMap field value if set, zero value otherwise.
func (o *ConfirmSourceMapUploadResponse) GetSourceMap() SourceMap {
	if o == nil || IsNil(o.SourceMap) {
		var ret SourceMap
		return ret
	}
	return *o.SourceMap
}

// GetSourceMapOk returns a tuple with the SourceMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfirmSourceMapUploadResponse) GetSourceMapOk() (*SourceMap, bool) {
	if o == nil || IsNil(o.SourceMap) {
		return nil, false
	}
	return o.SourceMap, true
}

// HasSourceMap returns a boolean if a field has been set.
func (o *ConfirmSourceMapUploadResponse) HasSourceMap() bool {
	if o != nil && !IsNil(o.SourceMap) {
		return true
	}

	return false
}

// SetSourceMap gets a reference to the given SourceMap and assigns it to the SourceMap field.
func (o *ConfirmSourceMapUploadResponse) SetSourceMap(v SourceMap) {
	o.SourceMap = &v
}

func (o ConfirmSourceMapUploadResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfirmSourceMapUploadResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SourceMap) {
		toSerialize["sourceMap"] = o.SourceMap
	}
	return toSerialize, nil
}

type NullableConfirmSourceMapUploadResponse struct {
	value *ConfirmSourceMapUploadResponse
	isSet bool
}

func (v NullableConfirmSourceMapUploadResponse) Get() *ConfirmSourceMapUploadResponse {
	return v.value
}

func (v *NullableConfirmSourceMapUploadResponse) Set(val *ConfirmSourceMapUploadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConfirmSourceMapUploadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConfirmSourceMapUploadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfirmSourceMapUploadResponse(val *ConfirmSourceMapUploadResponse) *NullableConfirmSourceMapUploadResponse {
	return &NullableConfirmSourceMapUploadResponse{value: val, isSet: true}
}

func (v NullableConfirmSourceMapUploadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfirmSourceMapUploadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


