/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the ListProductsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListProductsResponse{}

// ListProductsResponse struct for ListProductsResponse
type ListProductsResponse struct {
	Products []Product `json:"products,omitempty"`
	Pagination *PaginationResponse `json:"pagination,omitempty"`
	// Same page as products, each with a per-product rollup for the list page.
	Items []ProductWithSummary `json:"items,omitempty"`
}

// NewListProductsResponse instantiates a new ListProductsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListProductsResponse() *ListProductsResponse {
	this := ListProductsResponse{}
	return &this
}

// NewListProductsResponseWithDefaults instantiates a new ListProductsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListProductsResponseWithDefaults() *ListProductsResponse {
	this := ListProductsResponse{}
	return &this
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *ListProductsResponse) GetProducts() []Product {
	if o == nil || IsNil(o.Products) {
		var ret []Product
		return ret
	}
	return o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProductsResponse) GetProductsOk() ([]Product, bool) {
	if o == nil || IsNil(o.Products) {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *ListProductsResponse) HasProducts() bool {
	if o != nil && !IsNil(o.Products) {
		return true
	}

	return false
}

// SetProducts gets a reference to the given []Product and assigns it to the Products field.
func (o *ListProductsResponse) SetProducts(v []Product) {
	o.Products = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ListProductsResponse) GetPagination() PaginationResponse {
	if o == nil || IsNil(o.Pagination) {
		var ret PaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProductsResponse) GetPaginationOk() (*PaginationResponse, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ListProductsResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationResponse and assigns it to the Pagination field.
func (o *ListProductsResponse) SetPagination(v PaginationResponse) {
	o.Pagination = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ListProductsResponse) GetItems() []ProductWithSummary {
	if o == nil || IsNil(o.Items) {
		var ret []ProductWithSummary
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProductsResponse) GetItemsOk() ([]ProductWithSummary, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ListProductsResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ProductWithSummary and assigns it to the Items field.
func (o *ListProductsResponse) SetItems(v []ProductWithSummary) {
	o.Items = v
}

func (o ListProductsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListProductsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Products) {
		toSerialize["products"] = o.Products
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableListProductsResponse struct {
	value *ListProductsResponse
	isSet bool
}

func (v NullableListProductsResponse) Get() *ListProductsResponse {
	return v.value
}

func (v *NullableListProductsResponse) Set(val *ListProductsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListProductsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListProductsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListProductsResponse(val *ListProductsResponse) *NullableListProductsResponse {
	return &NullableListProductsResponse{value: val, isSet: true}
}

func (v NullableListProductsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListProductsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


