/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the PrepareTestGenerationContextResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrepareTestGenerationContextResponse{}

// PrepareTestGenerationContextResponse struct for PrepareTestGenerationContextResponse
type PrepareTestGenerationContextResponse struct {
	Context *PreparedTestGenerationContext `json:"context,omitempty"`
}

// NewPrepareTestGenerationContextResponse instantiates a new PrepareTestGenerationContextResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrepareTestGenerationContextResponse() *PrepareTestGenerationContextResponse {
	this := PrepareTestGenerationContextResponse{}
	return &this
}

// NewPrepareTestGenerationContextResponseWithDefaults instantiates a new PrepareTestGenerationContextResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrepareTestGenerationContextResponseWithDefaults() *PrepareTestGenerationContextResponse {
	this := PrepareTestGenerationContextResponse{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *PrepareTestGenerationContextResponse) GetContext() PreparedTestGenerationContext {
	if o == nil || IsNil(o.Context) {
		var ret PreparedTestGenerationContext
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrepareTestGenerationContextResponse) GetContextOk() (*PreparedTestGenerationContext, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *PrepareTestGenerationContextResponse) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given PreparedTestGenerationContext and assigns it to the Context field.
func (o *PrepareTestGenerationContextResponse) SetContext(v PreparedTestGenerationContext) {
	o.Context = &v
}

func (o PrepareTestGenerationContextResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrepareTestGenerationContextResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	return toSerialize, nil
}

type NullablePrepareTestGenerationContextResponse struct {
	value *PrepareTestGenerationContextResponse
	isSet bool
}

func (v NullablePrepareTestGenerationContextResponse) Get() *PrepareTestGenerationContextResponse {
	return v.value
}

func (v *NullablePrepareTestGenerationContextResponse) Set(val *PrepareTestGenerationContextResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePrepareTestGenerationContextResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePrepareTestGenerationContextResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrepareTestGenerationContextResponse(val *PrepareTestGenerationContextResponse) *NullablePrepareTestGenerationContextResponse {
	return &NullablePrepareTestGenerationContextResponse{value: val, isSet: true}
}

func (v NullablePrepareTestGenerationContextResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrepareTestGenerationContextResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


