/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the DistillIntentBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistillIntentBody{}

// DistillIntentBody DistillIntentRequest carries one coding session — the rendered transcript plus session metadata — to reconcile into the product's requirement tree.
type DistillIntentBody struct {
	// Rendered conversation (normalized, slim — user/assistant text only). Agent-specific transcript formats are not accepted.
	Transcript *string `json:"transcript,omitempty"`
	// Optional LLM credential to use. When empty, the backend picks the first usable llm.* credential in the product's workspace.
	CredentialId *string `json:"credentialId,omitempty"`
	// Optional model override; when empty, falls back to the credential's metadata \"model\" field.
	Model *string `json:"model,omitempty"`
	// Optional branch slug override; when empty, defaults to \"session\".
	Slug *string `json:"slug,omitempty"`
	// Repo-relative paths of files changed in the coding session (from git post-commit hook). The backend validates LLM-emitted repo_file anchors against this allowlist, dropping any path not in the set. Empty = no anchors written (backward-compatible: older CLI sends nothing).
	ChangedFiles []string `json:"changedFiles,omitempty"`
	// Coding-session identity. When either is set, every created/updated requirement gets a manual_input \"Intent capture\" provenance source carrying {sessionId, agent}, so a reviewer can trace it back to the session that produced it. Both empty (older CLI) writes no provenance source.
	SessionId *string `json:"sessionId,omitempty"`
	Agent *string `json:"agent,omitempty"`
}

// NewDistillIntentBody instantiates a new DistillIntentBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistillIntentBody() *DistillIntentBody {
	this := DistillIntentBody{}
	return &this
}

// NewDistillIntentBodyWithDefaults instantiates a new DistillIntentBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistillIntentBodyWithDefaults() *DistillIntentBody {
	this := DistillIntentBody{}
	return &this
}

// GetTranscript returns the Transcript field value if set, zero value otherwise.
func (o *DistillIntentBody) GetTranscript() string {
	if o == nil || IsNil(o.Transcript) {
		var ret string
		return ret
	}
	return *o.Transcript
}

// GetTranscriptOk returns a tuple with the Transcript field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentBody) GetTranscriptOk() (*string, bool) {
	if o == nil || IsNil(o.Transcript) {
		return nil, false
	}
	return o.Transcript, true
}

// HasTranscript returns a boolean if a field has been set.
func (o *DistillIntentBody) HasTranscript() bool {
	if o != nil && !IsNil(o.Transcript) {
		return true
	}

	return false
}

// SetTranscript gets a reference to the given string and assigns it to the Transcript field.
func (o *DistillIntentBody) SetTranscript(v string) {
	o.Transcript = &v
}

// GetCredentialId returns the CredentialId field value if set, zero value otherwise.
func (o *DistillIntentBody) GetCredentialId() string {
	if o == nil || IsNil(o.CredentialId) {
		var ret string
		return ret
	}
	return *o.CredentialId
}

// GetCredentialIdOk returns a tuple with the CredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentBody) GetCredentialIdOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialId) {
		return nil, false
	}
	return o.CredentialId, true
}

// HasCredentialId returns a boolean if a field has been set.
func (o *DistillIntentBody) HasCredentialId() bool {
	if o != nil && !IsNil(o.CredentialId) {
		return true
	}

	return false
}

// SetCredentialId gets a reference to the given string and assigns it to the CredentialId field.
func (o *DistillIntentBody) SetCredentialId(v string) {
	o.CredentialId = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *DistillIntentBody) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentBody) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *DistillIntentBody) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *DistillIntentBody) SetModel(v string) {
	o.Model = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *DistillIntentBody) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentBody) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *DistillIntentBody) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *DistillIntentBody) SetSlug(v string) {
	o.Slug = &v
}

// GetChangedFiles returns the ChangedFiles field value if set, zero value otherwise.
func (o *DistillIntentBody) GetChangedFiles() []string {
	if o == nil || IsNil(o.ChangedFiles) {
		var ret []string
		return ret
	}
	return o.ChangedFiles
}

// GetChangedFilesOk returns a tuple with the ChangedFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentBody) GetChangedFilesOk() ([]string, bool) {
	if o == nil || IsNil(o.ChangedFiles) {
		return nil, false
	}
	return o.ChangedFiles, true
}

// HasChangedFiles returns a boolean if a field has been set.
func (o *DistillIntentBody) HasChangedFiles() bool {
	if o != nil && !IsNil(o.ChangedFiles) {
		return true
	}

	return false
}

// SetChangedFiles gets a reference to the given []string and assigns it to the ChangedFiles field.
func (o *DistillIntentBody) SetChangedFiles(v []string) {
	o.ChangedFiles = v
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *DistillIntentBody) GetSessionId() string {
	if o == nil || IsNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentBody) GetSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *DistillIntentBody) HasSessionId() bool {
	if o != nil && !IsNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *DistillIntentBody) SetSessionId(v string) {
	o.SessionId = &v
}

// GetAgent returns the Agent field value if set, zero value otherwise.
func (o *DistillIntentBody) GetAgent() string {
	if o == nil || IsNil(o.Agent) {
		var ret string
		return ret
	}
	return *o.Agent
}

// GetAgentOk returns a tuple with the Agent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentBody) GetAgentOk() (*string, bool) {
	if o == nil || IsNil(o.Agent) {
		return nil, false
	}
	return o.Agent, true
}

// HasAgent returns a boolean if a field has been set.
func (o *DistillIntentBody) HasAgent() bool {
	if o != nil && !IsNil(o.Agent) {
		return true
	}

	return false
}

// SetAgent gets a reference to the given string and assigns it to the Agent field.
func (o *DistillIntentBody) SetAgent(v string) {
	o.Agent = &v
}

func (o DistillIntentBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistillIntentBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Transcript) {
		toSerialize["transcript"] = o.Transcript
	}
	if !IsNil(o.CredentialId) {
		toSerialize["credentialId"] = o.CredentialId
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.ChangedFiles) {
		toSerialize["changedFiles"] = o.ChangedFiles
	}
	if !IsNil(o.SessionId) {
		toSerialize["sessionId"] = o.SessionId
	}
	if !IsNil(o.Agent) {
		toSerialize["agent"] = o.Agent
	}
	return toSerialize, nil
}

type NullableDistillIntentBody struct {
	value *DistillIntentBody
	isSet bool
}

func (v NullableDistillIntentBody) Get() *DistillIntentBody {
	return v.value
}

func (v *NullableDistillIntentBody) Set(val *DistillIntentBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDistillIntentBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDistillIntentBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistillIntentBody(val *DistillIntentBody) *NullableDistillIntentBody {
	return &NullableDistillIntentBody{value: val, isSet: true}
}

func (v NullableDistillIntentBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistillIntentBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


