/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the BulkUpdateIssueStatusBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkUpdateIssueStatusBody{}

// BulkUpdateIssueStatusBody struct for BulkUpdateIssueStatusBody
type BulkUpdateIssueStatusBody struct {
	Ids []string `json:"ids,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewBulkUpdateIssueStatusBody instantiates a new BulkUpdateIssueStatusBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkUpdateIssueStatusBody() *BulkUpdateIssueStatusBody {
	this := BulkUpdateIssueStatusBody{}
	return &this
}

// NewBulkUpdateIssueStatusBodyWithDefaults instantiates a new BulkUpdateIssueStatusBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkUpdateIssueStatusBodyWithDefaults() *BulkUpdateIssueStatusBody {
	this := BulkUpdateIssueStatusBody{}
	return &this
}

// GetIds returns the Ids field value if set, zero value otherwise.
func (o *BulkUpdateIssueStatusBody) GetIds() []string {
	if o == nil || IsNil(o.Ids) {
		var ret []string
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkUpdateIssueStatusBody) GetIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *BulkUpdateIssueStatusBody) HasIds() bool {
	if o != nil && !IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []string and assigns it to the Ids field.
func (o *BulkUpdateIssueStatusBody) SetIds(v []string) {
	o.Ids = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BulkUpdateIssueStatusBody) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkUpdateIssueStatusBody) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BulkUpdateIssueStatusBody) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BulkUpdateIssueStatusBody) SetStatus(v string) {
	o.Status = &v
}

func (o BulkUpdateIssueStatusBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkUpdateIssueStatusBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ids) {
		toSerialize["ids"] = o.Ids
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableBulkUpdateIssueStatusBody struct {
	value *BulkUpdateIssueStatusBody
	isSet bool
}

func (v NullableBulkUpdateIssueStatusBody) Get() *BulkUpdateIssueStatusBody {
	return v.value
}

func (v *NullableBulkUpdateIssueStatusBody) Set(val *BulkUpdateIssueStatusBody) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkUpdateIssueStatusBody) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkUpdateIssueStatusBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkUpdateIssueStatusBody(val *BulkUpdateIssueStatusBody) *NullableBulkUpdateIssueStatusBody {
	return &NullableBulkUpdateIssueStatusBody{value: val, isSet: true}
}

func (v NullableBulkUpdateIssueStatusBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkUpdateIssueStatusBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


