/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the CreateTestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTestBody{}

// CreateTestBody struct for CreateTestBody
type CreateTestBody struct {
	Kind *string `json:"kind,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	ParentId *string `json:"parentId,omitempty"`
	Branch *string `json:"branch,omitempty"`
	Status *string `json:"status,omitempty"`
	Priority *string `json:"priority,omitempty"`
	Type *string `json:"type,omitempty"`
	Layer *string `json:"layer,omitempty"`
	Muted *bool `json:"muted,omitempty"`
	ComponentId *string `json:"componentId,omitempty"`
	AssigneeId *string `json:"assigneeId,omitempty"`
	Tags []string `json:"tags,omitempty"`
	CustomFields map[string]interface{} `json:"customFields,omitempty"`
	Steps []TestStep `json:"steps,omitempty"`
	Framework *string `json:"framework,omitempty"`
	FilePath *string `json:"filePath,omitempty"`
	IsAutomated *bool `json:"isAutomated,omitempty"`
	Signature *string `json:"signature,omitempty"`
	TestopsId *int32 `json:"testopsId,omitempty"`
	AuthorType *string `json:"authorType,omitempty"`
	AuthorId *string `json:"authorId,omitempty"`
	AuthorName *string `json:"authorName,omitempty"`
	ParameterGroups []TestParameterGroup `json:"parameterGroups,omitempty"`
	LatestExecution *TestExecution `json:"latestExecution,omitempty"`
	Attachments []string `json:"attachments,omitempty"`
	Relations []TestRelation `json:"relations,omitempty"`
}

// NewCreateTestBody instantiates a new CreateTestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTestBody() *CreateTestBody {
	this := CreateTestBody{}
	return &this
}

// NewCreateTestBodyWithDefaults instantiates a new CreateTestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTestBodyWithDefaults() *CreateTestBody {
	this := CreateTestBody{}
	return &this
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *CreateTestBody) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *CreateTestBody) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *CreateTestBody) SetKind(v string) {
	o.Kind = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CreateTestBody) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CreateTestBody) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CreateTestBody) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateTestBody) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateTestBody) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateTestBody) SetDescription(v string) {
	o.Description = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *CreateTestBody) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *CreateTestBody) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *CreateTestBody) SetParentId(v string) {
	o.ParentId = &v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *CreateTestBody) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *CreateTestBody) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *CreateTestBody) SetBranch(v string) {
	o.Branch = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateTestBody) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateTestBody) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreateTestBody) SetStatus(v string) {
	o.Status = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *CreateTestBody) GetPriority() string {
	if o == nil || IsNil(o.Priority) {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *CreateTestBody) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *CreateTestBody) SetPriority(v string) {
	o.Priority = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateTestBody) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateTestBody) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateTestBody) SetType(v string) {
	o.Type = &v
}

// GetLayer returns the Layer field value if set, zero value otherwise.
func (o *CreateTestBody) GetLayer() string {
	if o == nil || IsNil(o.Layer) {
		var ret string
		return ret
	}
	return *o.Layer
}

// GetLayerOk returns a tuple with the Layer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetLayerOk() (*string, bool) {
	if o == nil || IsNil(o.Layer) {
		return nil, false
	}
	return o.Layer, true
}

// HasLayer returns a boolean if a field has been set.
func (o *CreateTestBody) HasLayer() bool {
	if o != nil && !IsNil(o.Layer) {
		return true
	}

	return false
}

// SetLayer gets a reference to the given string and assigns it to the Layer field.
func (o *CreateTestBody) SetLayer(v string) {
	o.Layer = &v
}

// GetMuted returns the Muted field value if set, zero value otherwise.
func (o *CreateTestBody) GetMuted() bool {
	if o == nil || IsNil(o.Muted) {
		var ret bool
		return ret
	}
	return *o.Muted
}

// GetMutedOk returns a tuple with the Muted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetMutedOk() (*bool, bool) {
	if o == nil || IsNil(o.Muted) {
		return nil, false
	}
	return o.Muted, true
}

// HasMuted returns a boolean if a field has been set.
func (o *CreateTestBody) HasMuted() bool {
	if o != nil && !IsNil(o.Muted) {
		return true
	}

	return false
}

// SetMuted gets a reference to the given bool and assigns it to the Muted field.
func (o *CreateTestBody) SetMuted(v bool) {
	o.Muted = &v
}

// GetComponentId returns the ComponentId field value if set, zero value otherwise.
func (o *CreateTestBody) GetComponentId() string {
	if o == nil || IsNil(o.ComponentId) {
		var ret string
		return ret
	}
	return *o.ComponentId
}

// GetComponentIdOk returns a tuple with the ComponentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetComponentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ComponentId) {
		return nil, false
	}
	return o.ComponentId, true
}

// HasComponentId returns a boolean if a field has been set.
func (o *CreateTestBody) HasComponentId() bool {
	if o != nil && !IsNil(o.ComponentId) {
		return true
	}

	return false
}

// SetComponentId gets a reference to the given string and assigns it to the ComponentId field.
func (o *CreateTestBody) SetComponentId(v string) {
	o.ComponentId = &v
}

// GetAssigneeId returns the AssigneeId field value if set, zero value otherwise.
func (o *CreateTestBody) GetAssigneeId() string {
	if o == nil || IsNil(o.AssigneeId) {
		var ret string
		return ret
	}
	return *o.AssigneeId
}

// GetAssigneeIdOk returns a tuple with the AssigneeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetAssigneeIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssigneeId) {
		return nil, false
	}
	return o.AssigneeId, true
}

// HasAssigneeId returns a boolean if a field has been set.
func (o *CreateTestBody) HasAssigneeId() bool {
	if o != nil && !IsNil(o.AssigneeId) {
		return true
	}

	return false
}

// SetAssigneeId gets a reference to the given string and assigns it to the AssigneeId field.
func (o *CreateTestBody) SetAssigneeId(v string) {
	o.AssigneeId = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CreateTestBody) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateTestBody) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CreateTestBody) SetTags(v []string) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *CreateTestBody) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *CreateTestBody) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *CreateTestBody) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *CreateTestBody) GetSteps() []TestStep {
	if o == nil || IsNil(o.Steps) {
		var ret []TestStep
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetStepsOk() ([]TestStep, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *CreateTestBody) HasSteps() bool {
	if o != nil && !IsNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []TestStep and assigns it to the Steps field.
func (o *CreateTestBody) SetSteps(v []TestStep) {
	o.Steps = v
}

// GetFramework returns the Framework field value if set, zero value otherwise.
func (o *CreateTestBody) GetFramework() string {
	if o == nil || IsNil(o.Framework) {
		var ret string
		return ret
	}
	return *o.Framework
}

// GetFrameworkOk returns a tuple with the Framework field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetFrameworkOk() (*string, bool) {
	if o == nil || IsNil(o.Framework) {
		return nil, false
	}
	return o.Framework, true
}

// HasFramework returns a boolean if a field has been set.
func (o *CreateTestBody) HasFramework() bool {
	if o != nil && !IsNil(o.Framework) {
		return true
	}

	return false
}

// SetFramework gets a reference to the given string and assigns it to the Framework field.
func (o *CreateTestBody) SetFramework(v string) {
	o.Framework = &v
}

// GetFilePath returns the FilePath field value if set, zero value otherwise.
func (o *CreateTestBody) GetFilePath() string {
	if o == nil || IsNil(o.FilePath) {
		var ret string
		return ret
	}
	return *o.FilePath
}

// GetFilePathOk returns a tuple with the FilePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetFilePathOk() (*string, bool) {
	if o == nil || IsNil(o.FilePath) {
		return nil, false
	}
	return o.FilePath, true
}

// HasFilePath returns a boolean if a field has been set.
func (o *CreateTestBody) HasFilePath() bool {
	if o != nil && !IsNil(o.FilePath) {
		return true
	}

	return false
}

// SetFilePath gets a reference to the given string and assigns it to the FilePath field.
func (o *CreateTestBody) SetFilePath(v string) {
	o.FilePath = &v
}

// GetIsAutomated returns the IsAutomated field value if set, zero value otherwise.
func (o *CreateTestBody) GetIsAutomated() bool {
	if o == nil || IsNil(o.IsAutomated) {
		var ret bool
		return ret
	}
	return *o.IsAutomated
}

// GetIsAutomatedOk returns a tuple with the IsAutomated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetIsAutomatedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAutomated) {
		return nil, false
	}
	return o.IsAutomated, true
}

// HasIsAutomated returns a boolean if a field has been set.
func (o *CreateTestBody) HasIsAutomated() bool {
	if o != nil && !IsNil(o.IsAutomated) {
		return true
	}

	return false
}

// SetIsAutomated gets a reference to the given bool and assigns it to the IsAutomated field.
func (o *CreateTestBody) SetIsAutomated(v bool) {
	o.IsAutomated = &v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *CreateTestBody) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *CreateTestBody) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *CreateTestBody) SetSignature(v string) {
	o.Signature = &v
}

// GetTestopsId returns the TestopsId field value if set, zero value otherwise.
func (o *CreateTestBody) GetTestopsId() int32 {
	if o == nil || IsNil(o.TestopsId) {
		var ret int32
		return ret
	}
	return *o.TestopsId
}

// GetTestopsIdOk returns a tuple with the TestopsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetTestopsIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TestopsId) {
		return nil, false
	}
	return o.TestopsId, true
}

// HasTestopsId returns a boolean if a field has been set.
func (o *CreateTestBody) HasTestopsId() bool {
	if o != nil && !IsNil(o.TestopsId) {
		return true
	}

	return false
}

// SetTestopsId gets a reference to the given int32 and assigns it to the TestopsId field.
func (o *CreateTestBody) SetTestopsId(v int32) {
	o.TestopsId = &v
}

// GetAuthorType returns the AuthorType field value if set, zero value otherwise.
func (o *CreateTestBody) GetAuthorType() string {
	if o == nil || IsNil(o.AuthorType) {
		var ret string
		return ret
	}
	return *o.AuthorType
}

// GetAuthorTypeOk returns a tuple with the AuthorType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetAuthorTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorType) {
		return nil, false
	}
	return o.AuthorType, true
}

// HasAuthorType returns a boolean if a field has been set.
func (o *CreateTestBody) HasAuthorType() bool {
	if o != nil && !IsNil(o.AuthorType) {
		return true
	}

	return false
}

// SetAuthorType gets a reference to the given string and assigns it to the AuthorType field.
func (o *CreateTestBody) SetAuthorType(v string) {
	o.AuthorType = &v
}

// GetAuthorId returns the AuthorId field value if set, zero value otherwise.
func (o *CreateTestBody) GetAuthorId() string {
	if o == nil || IsNil(o.AuthorId) {
		var ret string
		return ret
	}
	return *o.AuthorId
}

// GetAuthorIdOk returns a tuple with the AuthorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetAuthorIdOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorId) {
		return nil, false
	}
	return o.AuthorId, true
}

// HasAuthorId returns a boolean if a field has been set.
func (o *CreateTestBody) HasAuthorId() bool {
	if o != nil && !IsNil(o.AuthorId) {
		return true
	}

	return false
}

// SetAuthorId gets a reference to the given string and assigns it to the AuthorId field.
func (o *CreateTestBody) SetAuthorId(v string) {
	o.AuthorId = &v
}

// GetAuthorName returns the AuthorName field value if set, zero value otherwise.
func (o *CreateTestBody) GetAuthorName() string {
	if o == nil || IsNil(o.AuthorName) {
		var ret string
		return ret
	}
	return *o.AuthorName
}

// GetAuthorNameOk returns a tuple with the AuthorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetAuthorNameOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorName) {
		return nil, false
	}
	return o.AuthorName, true
}

// HasAuthorName returns a boolean if a field has been set.
func (o *CreateTestBody) HasAuthorName() bool {
	if o != nil && !IsNil(o.AuthorName) {
		return true
	}

	return false
}

// SetAuthorName gets a reference to the given string and assigns it to the AuthorName field.
func (o *CreateTestBody) SetAuthorName(v string) {
	o.AuthorName = &v
}

// GetParameterGroups returns the ParameterGroups field value if set, zero value otherwise.
func (o *CreateTestBody) GetParameterGroups() []TestParameterGroup {
	if o == nil || IsNil(o.ParameterGroups) {
		var ret []TestParameterGroup
		return ret
	}
	return o.ParameterGroups
}

// GetParameterGroupsOk returns a tuple with the ParameterGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetParameterGroupsOk() ([]TestParameterGroup, bool) {
	if o == nil || IsNil(o.ParameterGroups) {
		return nil, false
	}
	return o.ParameterGroups, true
}

// HasParameterGroups returns a boolean if a field has been set.
func (o *CreateTestBody) HasParameterGroups() bool {
	if o != nil && !IsNil(o.ParameterGroups) {
		return true
	}

	return false
}

// SetParameterGroups gets a reference to the given []TestParameterGroup and assigns it to the ParameterGroups field.
func (o *CreateTestBody) SetParameterGroups(v []TestParameterGroup) {
	o.ParameterGroups = v
}

// GetLatestExecution returns the LatestExecution field value if set, zero value otherwise.
func (o *CreateTestBody) GetLatestExecution() TestExecution {
	if o == nil || IsNil(o.LatestExecution) {
		var ret TestExecution
		return ret
	}
	return *o.LatestExecution
}

// GetLatestExecutionOk returns a tuple with the LatestExecution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetLatestExecutionOk() (*TestExecution, bool) {
	if o == nil || IsNil(o.LatestExecution) {
		return nil, false
	}
	return o.LatestExecution, true
}

// HasLatestExecution returns a boolean if a field has been set.
func (o *CreateTestBody) HasLatestExecution() bool {
	if o != nil && !IsNil(o.LatestExecution) {
		return true
	}

	return false
}

// SetLatestExecution gets a reference to the given TestExecution and assigns it to the LatestExecution field.
func (o *CreateTestBody) SetLatestExecution(v TestExecution) {
	o.LatestExecution = &v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *CreateTestBody) GetAttachments() []string {
	if o == nil || IsNil(o.Attachments) {
		var ret []string
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetAttachmentsOk() ([]string, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *CreateTestBody) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []string and assigns it to the Attachments field.
func (o *CreateTestBody) SetAttachments(v []string) {
	o.Attachments = v
}

// GetRelations returns the Relations field value if set, zero value otherwise.
func (o *CreateTestBody) GetRelations() []TestRelation {
	if o == nil || IsNil(o.Relations) {
		var ret []TestRelation
		return ret
	}
	return o.Relations
}

// GetRelationsOk returns a tuple with the Relations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTestBody) GetRelationsOk() ([]TestRelation, bool) {
	if o == nil || IsNil(o.Relations) {
		return nil, false
	}
	return o.Relations, true
}

// HasRelations returns a boolean if a field has been set.
func (o *CreateTestBody) HasRelations() bool {
	if o != nil && !IsNil(o.Relations) {
		return true
	}

	return false
}

// SetRelations gets a reference to the given []TestRelation and assigns it to the Relations field.
func (o *CreateTestBody) SetRelations(v []TestRelation) {
	o.Relations = v
}

func (o CreateTestBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ParentId) {
		toSerialize["parentId"] = o.ParentId
	}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Layer) {
		toSerialize["layer"] = o.Layer
	}
	if !IsNil(o.Muted) {
		toSerialize["muted"] = o.Muted
	}
	if !IsNil(o.ComponentId) {
		toSerialize["componentId"] = o.ComponentId
	}
	if !IsNil(o.AssigneeId) {
		toSerialize["assigneeId"] = o.AssigneeId
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["customFields"] = o.CustomFields
	}
	if !IsNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}
	if !IsNil(o.Framework) {
		toSerialize["framework"] = o.Framework
	}
	if !IsNil(o.FilePath) {
		toSerialize["filePath"] = o.FilePath
	}
	if !IsNil(o.IsAutomated) {
		toSerialize["isAutomated"] = o.IsAutomated
	}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	if !IsNil(o.TestopsId) {
		toSerialize["testopsId"] = o.TestopsId
	}
	if !IsNil(o.AuthorType) {
		toSerialize["authorType"] = o.AuthorType
	}
	if !IsNil(o.AuthorId) {
		toSerialize["authorId"] = o.AuthorId
	}
	if !IsNil(o.AuthorName) {
		toSerialize["authorName"] = o.AuthorName
	}
	if !IsNil(o.ParameterGroups) {
		toSerialize["parameterGroups"] = o.ParameterGroups
	}
	if !IsNil(o.LatestExecution) {
		toSerialize["latestExecution"] = o.LatestExecution
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	if !IsNil(o.Relations) {
		toSerialize["relations"] = o.Relations
	}
	return toSerialize, nil
}

type NullableCreateTestBody struct {
	value *CreateTestBody
	isSet bool
}

func (v NullableCreateTestBody) Get() *CreateTestBody {
	return v.value
}

func (v *NullableCreateTestBody) Set(val *CreateTestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTestBody(val *CreateTestBody) *NullableCreateTestBody {
	return &NullableCreateTestBody{value: val, isSet: true}
}

func (v NullableCreateTestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


