/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the V1UploadRunAttachmentsError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1UploadRunAttachmentsError{}

// V1UploadRunAttachmentsError struct for V1UploadRunAttachmentsError
type V1UploadRunAttachmentsError struct {
	// Always false.
	Status *bool `json:"status,omitempty"`
	Error *string `json:"error,omitempty"`
}

// NewV1UploadRunAttachmentsError instantiates a new V1UploadRunAttachmentsError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1UploadRunAttachmentsError() *V1UploadRunAttachmentsError {
	this := V1UploadRunAttachmentsError{}
	return &this
}

// NewV1UploadRunAttachmentsErrorWithDefaults instantiates a new V1UploadRunAttachmentsError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1UploadRunAttachmentsErrorWithDefaults() *V1UploadRunAttachmentsError {
	this := V1UploadRunAttachmentsError{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1UploadRunAttachmentsError) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UploadRunAttachmentsError) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1UploadRunAttachmentsError) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *V1UploadRunAttachmentsError) SetStatus(v bool) {
	o.Status = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *V1UploadRunAttachmentsError) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1UploadRunAttachmentsError) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *V1UploadRunAttachmentsError) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *V1UploadRunAttachmentsError) SetError(v string) {
	o.Error = &v
}

func (o V1UploadRunAttachmentsError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1UploadRunAttachmentsError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableV1UploadRunAttachmentsError struct {
	value *V1UploadRunAttachmentsError
	isSet bool
}

func (v NullableV1UploadRunAttachmentsError) Get() *V1UploadRunAttachmentsError {
	return v.value
}

func (v *NullableV1UploadRunAttachmentsError) Set(val *V1UploadRunAttachmentsError) {
	v.value = val
	v.isSet = true
}

func (v NullableV1UploadRunAttachmentsError) IsSet() bool {
	return v.isSet
}

func (v *NullableV1UploadRunAttachmentsError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1UploadRunAttachmentsError(val *V1UploadRunAttachmentsError) *NullableV1UploadRunAttachmentsError {
	return &NullableV1UploadRunAttachmentsError{value: val, isSet: true}
}

func (v NullableV1UploadRunAttachmentsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1UploadRunAttachmentsError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


