/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the GetAgentRunResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAgentRunResponse{}

// GetAgentRunResponse struct for GetAgentRunResponse
type GetAgentRunResponse struct {
	Run *AgentRun `json:"run,omitempty"`
}

// NewGetAgentRunResponse instantiates a new GetAgentRunResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAgentRunResponse() *GetAgentRunResponse {
	this := GetAgentRunResponse{}
	return &this
}

// NewGetAgentRunResponseWithDefaults instantiates a new GetAgentRunResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAgentRunResponseWithDefaults() *GetAgentRunResponse {
	this := GetAgentRunResponse{}
	return &this
}

// GetRun returns the Run field value if set, zero value otherwise.
func (o *GetAgentRunResponse) GetRun() AgentRun {
	if o == nil || IsNil(o.Run) {
		var ret AgentRun
		return ret
	}
	return *o.Run
}

// GetRunOk returns a tuple with the Run field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAgentRunResponse) GetRunOk() (*AgentRun, bool) {
	if o == nil || IsNil(o.Run) {
		return nil, false
	}
	return o.Run, true
}

// HasRun returns a boolean if a field has been set.
func (o *GetAgentRunResponse) HasRun() bool {
	if o != nil && !IsNil(o.Run) {
		return true
	}

	return false
}

// SetRun gets a reference to the given AgentRun and assigns it to the Run field.
func (o *GetAgentRunResponse) SetRun(v AgentRun) {
	o.Run = &v
}

func (o GetAgentRunResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAgentRunResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Run) {
		toSerialize["run"] = o.Run
	}
	return toSerialize, nil
}

type NullableGetAgentRunResponse struct {
	value *GetAgentRunResponse
	isSet bool
}

func (v NullableGetAgentRunResponse) Get() *GetAgentRunResponse {
	return v.value
}

func (v *NullableGetAgentRunResponse) Set(val *GetAgentRunResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAgentRunResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAgentRunResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAgentRunResponse(val *GetAgentRunResponse) *NullableGetAgentRunResponse {
	return &NullableGetAgentRunResponse{value: val, isSet: true}
}

func (v NullableGetAgentRunResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAgentRunResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


