/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the GetAgentConfigResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAgentConfigResponse{}

// GetAgentConfigResponse struct for GetAgentConfigResponse
type GetAgentConfigResponse struct {
	Config *AgentConfig `json:"config,omitempty"`
}

// NewGetAgentConfigResponse instantiates a new GetAgentConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAgentConfigResponse() *GetAgentConfigResponse {
	this := GetAgentConfigResponse{}
	return &this
}

// NewGetAgentConfigResponseWithDefaults instantiates a new GetAgentConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAgentConfigResponseWithDefaults() *GetAgentConfigResponse {
	this := GetAgentConfigResponse{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *GetAgentConfigResponse) GetConfig() AgentConfig {
	if o == nil || IsNil(o.Config) {
		var ret AgentConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAgentConfigResponse) GetConfigOk() (*AgentConfig, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *GetAgentConfigResponse) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given AgentConfig and assigns it to the Config field.
func (o *GetAgentConfigResponse) SetConfig(v AgentConfig) {
	o.Config = &v
}

func (o GetAgentConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAgentConfigResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableGetAgentConfigResponse struct {
	value *GetAgentConfigResponse
	isSet bool
}

func (v NullableGetAgentConfigResponse) Get() *GetAgentConfigResponse {
	return v.value
}

func (v *NullableGetAgentConfigResponse) Set(val *GetAgentConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAgentConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAgentConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAgentConfigResponse(val *GetAgentConfigResponse) *NullableGetAgentConfigResponse {
	return &NullableGetAgentConfigResponse{value: val, isSet: true}
}

func (v NullableGetAgentConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAgentConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


