/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the DistillIntentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistillIntentResponse{}

// DistillIntentResponse struct for DistillIntentResponse
type DistillIntentResponse struct {
	// Name of the intent branch the changes were written to (empty when skipped).
	IntentBranch *string `json:"intentBranch,omitempty"`
	Created *int32 `json:"created,omitempty"`
	Updated *int32 `json:"updated,omitempty"`
	Dropped *int32 `json:"dropped,omitempty"`
	Skipped *bool `json:"skipped,omitempty"`
	SkipReason *string `json:"skipReason,omitempty"`
}

// NewDistillIntentResponse instantiates a new DistillIntentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistillIntentResponse() *DistillIntentResponse {
	this := DistillIntentResponse{}
	return &this
}

// NewDistillIntentResponseWithDefaults instantiates a new DistillIntentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistillIntentResponseWithDefaults() *DistillIntentResponse {
	this := DistillIntentResponse{}
	return &this
}

// GetIntentBranch returns the IntentBranch field value if set, zero value otherwise.
func (o *DistillIntentResponse) GetIntentBranch() string {
	if o == nil || IsNil(o.IntentBranch) {
		var ret string
		return ret
	}
	return *o.IntentBranch
}

// GetIntentBranchOk returns a tuple with the IntentBranch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentResponse) GetIntentBranchOk() (*string, bool) {
	if o == nil || IsNil(o.IntentBranch) {
		return nil, false
	}
	return o.IntentBranch, true
}

// HasIntentBranch returns a boolean if a field has been set.
func (o *DistillIntentResponse) HasIntentBranch() bool {
	if o != nil && !IsNil(o.IntentBranch) {
		return true
	}

	return false
}

// SetIntentBranch gets a reference to the given string and assigns it to the IntentBranch field.
func (o *DistillIntentResponse) SetIntentBranch(v string) {
	o.IntentBranch = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *DistillIntentResponse) GetCreated() int32 {
	if o == nil || IsNil(o.Created) {
		var ret int32
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentResponse) GetCreatedOk() (*int32, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *DistillIntentResponse) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given int32 and assigns it to the Created field.
func (o *DistillIntentResponse) SetCreated(v int32) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *DistillIntentResponse) GetUpdated() int32 {
	if o == nil || IsNil(o.Updated) {
		var ret int32
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentResponse) GetUpdatedOk() (*int32, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *DistillIntentResponse) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given int32 and assigns it to the Updated field.
func (o *DistillIntentResponse) SetUpdated(v int32) {
	o.Updated = &v
}

// GetDropped returns the Dropped field value if set, zero value otherwise.
func (o *DistillIntentResponse) GetDropped() int32 {
	if o == nil || IsNil(o.Dropped) {
		var ret int32
		return ret
	}
	return *o.Dropped
}

// GetDroppedOk returns a tuple with the Dropped field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentResponse) GetDroppedOk() (*int32, bool) {
	if o == nil || IsNil(o.Dropped) {
		return nil, false
	}
	return o.Dropped, true
}

// HasDropped returns a boolean if a field has been set.
func (o *DistillIntentResponse) HasDropped() bool {
	if o != nil && !IsNil(o.Dropped) {
		return true
	}

	return false
}

// SetDropped gets a reference to the given int32 and assigns it to the Dropped field.
func (o *DistillIntentResponse) SetDropped(v int32) {
	o.Dropped = &v
}

// GetSkipped returns the Skipped field value if set, zero value otherwise.
func (o *DistillIntentResponse) GetSkipped() bool {
	if o == nil || IsNil(o.Skipped) {
		var ret bool
		return ret
	}
	return *o.Skipped
}

// GetSkippedOk returns a tuple with the Skipped field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentResponse) GetSkippedOk() (*bool, bool) {
	if o == nil || IsNil(o.Skipped) {
		return nil, false
	}
	return o.Skipped, true
}

// HasSkipped returns a boolean if a field has been set.
func (o *DistillIntentResponse) HasSkipped() bool {
	if o != nil && !IsNil(o.Skipped) {
		return true
	}

	return false
}

// SetSkipped gets a reference to the given bool and assigns it to the Skipped field.
func (o *DistillIntentResponse) SetSkipped(v bool) {
	o.Skipped = &v
}

// GetSkipReason returns the SkipReason field value if set, zero value otherwise.
func (o *DistillIntentResponse) GetSkipReason() string {
	if o == nil || IsNil(o.SkipReason) {
		var ret string
		return ret
	}
	return *o.SkipReason
}

// GetSkipReasonOk returns a tuple with the SkipReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistillIntentResponse) GetSkipReasonOk() (*string, bool) {
	if o == nil || IsNil(o.SkipReason) {
		return nil, false
	}
	return o.SkipReason, true
}

// HasSkipReason returns a boolean if a field has been set.
func (o *DistillIntentResponse) HasSkipReason() bool {
	if o != nil && !IsNil(o.SkipReason) {
		return true
	}

	return false
}

// SetSkipReason gets a reference to the given string and assigns it to the SkipReason field.
func (o *DistillIntentResponse) SetSkipReason(v string) {
	o.SkipReason = &v
}

func (o DistillIntentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistillIntentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IntentBranch) {
		toSerialize["intentBranch"] = o.IntentBranch
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if !IsNil(o.Dropped) {
		toSerialize["dropped"] = o.Dropped
	}
	if !IsNil(o.Skipped) {
		toSerialize["skipped"] = o.Skipped
	}
	if !IsNil(o.SkipReason) {
		toSerialize["skipReason"] = o.SkipReason
	}
	return toSerialize, nil
}

type NullableDistillIntentResponse struct {
	value *DistillIntentResponse
	isSet bool
}

func (v NullableDistillIntentResponse) Get() *DistillIntentResponse {
	return v.value
}

func (v *NullableDistillIntentResponse) Set(val *DistillIntentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDistillIntentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDistillIntentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistillIntentResponse(val *DistillIntentResponse) *NullableDistillIntentResponse {
	return &NullableDistillIntentResponse{value: val, isSet: true}
}

func (v NullableDistillIntentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistillIntentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


