/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the FileAnchorCandidate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileAnchorCandidate{}

// FileAnchorCandidate FileAnchorCandidate is one proposed (requirement, test) link from shared source-file proximity. exact = the test's file_path equals a requirement repo_file anchor (auto-linked); otherwise a directory-proximity candidate for agent confirmation.
type FileAnchorCandidate struct {
	RequirementId *string `json:"requirementId,omitempty"`
	RequirementSeq *int32 `json:"requirementSeq,omitempty"`
	RequirementTitle *string `json:"requirementTitle,omitempty"`
	TestId *string `json:"testId,omitempty"`
	TestSeq *int32 `json:"testSeq,omitempty"`
	TestTitle *string `json:"testTitle,omitempty"`
	TestFilePath *string `json:"testFilePath,omitempty"`
	AnchorPath *string `json:"anchorPath,omitempty"`
	Dir *string `json:"dir,omitempty"`
	Exact *bool `json:"exact,omitempty"`
	Confidence *float64 `json:"confidence,omitempty"`
}

// NewFileAnchorCandidate instantiates a new FileAnchorCandidate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileAnchorCandidate() *FileAnchorCandidate {
	this := FileAnchorCandidate{}
	return &this
}

// NewFileAnchorCandidateWithDefaults instantiates a new FileAnchorCandidate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileAnchorCandidateWithDefaults() *FileAnchorCandidate {
	this := FileAnchorCandidate{}
	return &this
}

// GetRequirementId returns the RequirementId field value if set, zero value otherwise.
func (o *FileAnchorCandidate) GetRequirementId() string {
	if o == nil || IsNil(o.RequirementId) {
		var ret string
		return ret
	}
	return *o.RequirementId
}

// GetRequirementIdOk returns a tuple with the RequirementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileAnchorCandidate) GetRequirementIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequirementId) {
		return nil, false
	}
	return o.RequirementId, true
}

// HasRequirementId returns a boolean if a field has been set.
func (o *FileAnchorCandidate) HasRequirementId() bool {
	if o != nil && !IsNil(o.RequirementId) {
		return true
	}

	return false
}

// SetRequirementId gets a reference to the given string and assigns it to the RequirementId field.
func (o *FileAnchorCandidate) SetRequirementId(v string) {
	o.RequirementId = &v
}

// GetRequirementSeq returns the RequirementSeq field value if set, zero value otherwise.
func (o *FileAnchorCandidate) GetRequirementSeq() int32 {
	if o == nil || IsNil(o.RequirementSeq) {
		var ret int32
		return ret
	}
	return *o.RequirementSeq
}

// GetRequirementSeqOk returns a tuple with the RequirementSeq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileAnchorCandidate) GetRequirementSeqOk() (*int32, bool) {
	if o == nil || IsNil(o.RequirementSeq) {
		return nil, false
	}
	return o.RequirementSeq, true
}

// HasRequirementSeq returns a boolean if a field has been set.
func (o *FileAnchorCandidate) HasRequirementSeq() bool {
	if o != nil && !IsNil(o.RequirementSeq) {
		return true
	}

	return false
}

// SetRequirementSeq gets a reference to the given int32 and assigns it to the RequirementSeq field.
func (o *FileAnchorCandidate) SetRequirementSeq(v int32) {
	o.RequirementSeq = &v
}

// GetRequirementTitle returns the RequirementTitle field value if set, zero value otherwise.
func (o *FileAnchorCandidate) GetRequirementTitle() string {
	if o == nil || IsNil(o.RequirementTitle) {
		var ret string
		return ret
	}
	return *o.RequirementTitle
}

// GetRequirementTitleOk returns a tuple with the RequirementTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileAnchorCandidate) GetRequirementTitleOk() (*string, bool) {
	if o == nil || IsNil(o.RequirementTitle) {
		return nil, false
	}
	return o.RequirementTitle, true
}

// HasRequirementTitle returns a boolean if a field has been set.
func (o *FileAnchorCandidate) HasRequirementTitle() bool {
	if o != nil && !IsNil(o.RequirementTitle) {
		return true
	}

	return false
}

// SetRequirementTitle gets a reference to the given string and assigns it to the RequirementTitle field.
func (o *FileAnchorCandidate) SetRequirementTitle(v string) {
	o.RequirementTitle = &v
}

// GetTestId returns the TestId field value if set, zero value otherwise.
func (o *FileAnchorCandidate) GetTestId() string {
	if o == nil || IsNil(o.TestId) {
		var ret string
		return ret
	}
	return *o.TestId
}

// GetTestIdOk returns a tuple with the TestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileAnchorCandidate) GetTestIdOk() (*string, bool) {
	if o == nil || IsNil(o.TestId) {
		return nil, false
	}
	return o.TestId, true
}

// HasTestId returns a boolean if a field has been set.
func (o *FileAnchorCandidate) HasTestId() bool {
	if o != nil && !IsNil(o.TestId) {
		return true
	}

	return false
}

// SetTestId gets a reference to the given string and assigns it to the TestId field.
func (o *FileAnchorCandidate) SetTestId(v string) {
	o.TestId = &v
}

// GetTestSeq returns the TestSeq field value if set, zero value otherwise.
func (o *FileAnchorCandidate) GetTestSeq() int32 {
	if o == nil || IsNil(o.TestSeq) {
		var ret int32
		return ret
	}
	return *o.TestSeq
}

// GetTestSeqOk returns a tuple with the TestSeq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileAnchorCandidate) GetTestSeqOk() (*int32, bool) {
	if o == nil || IsNil(o.TestSeq) {
		return nil, false
	}
	return o.TestSeq, true
}

// HasTestSeq returns a boolean if a field has been set.
func (o *FileAnchorCandidate) HasTestSeq() bool {
	if o != nil && !IsNil(o.TestSeq) {
		return true
	}

	return false
}

// SetTestSeq gets a reference to the given int32 and assigns it to the TestSeq field.
func (o *FileAnchorCandidate) SetTestSeq(v int32) {
	o.TestSeq = &v
}

// GetTestTitle returns the TestTitle field value if set, zero value otherwise.
func (o *FileAnchorCandidate) GetTestTitle() string {
	if o == nil || IsNil(o.TestTitle) {
		var ret string
		return ret
	}
	return *o.TestTitle
}

// GetTestTitleOk returns a tuple with the TestTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileAnchorCandidate) GetTestTitleOk() (*string, bool) {
	if o == nil || IsNil(o.TestTitle) {
		return nil, false
	}
	return o.TestTitle, true
}

// HasTestTitle returns a boolean if a field has been set.
func (o *FileAnchorCandidate) HasTestTitle() bool {
	if o != nil && !IsNil(o.TestTitle) {
		return true
	}

	return false
}

// SetTestTitle gets a reference to the given string and assigns it to the TestTitle field.
func (o *FileAnchorCandidate) SetTestTitle(v string) {
	o.TestTitle = &v
}

// GetTestFilePath returns the TestFilePath field value if set, zero value otherwise.
func (o *FileAnchorCandidate) GetTestFilePath() string {
	if o == nil || IsNil(o.TestFilePath) {
		var ret string
		return ret
	}
	return *o.TestFilePath
}

// GetTestFilePathOk returns a tuple with the TestFilePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileAnchorCandidate) GetTestFilePathOk() (*string, bool) {
	if o == nil || IsNil(o.TestFilePath) {
		return nil, false
	}
	return o.TestFilePath, true
}

// HasTestFilePath returns a boolean if a field has been set.
func (o *FileAnchorCandidate) HasTestFilePath() bool {
	if o != nil && !IsNil(o.TestFilePath) {
		return true
	}

	return false
}

// SetTestFilePath gets a reference to the given string and assigns it to the TestFilePath field.
func (o *FileAnchorCandidate) SetTestFilePath(v string) {
	o.TestFilePath = &v
}

// GetAnchorPath returns the AnchorPath field value if set, zero value otherwise.
func (o *FileAnchorCandidate) GetAnchorPath() string {
	if o == nil || IsNil(o.AnchorPath) {
		var ret string
		return ret
	}
	return *o.AnchorPath
}

// GetAnchorPathOk returns a tuple with the AnchorPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileAnchorCandidate) GetAnchorPathOk() (*string, bool) {
	if o == nil || IsNil(o.AnchorPath) {
		return nil, false
	}
	return o.AnchorPath, true
}

// HasAnchorPath returns a boolean if a field has been set.
func (o *FileAnchorCandidate) HasAnchorPath() bool {
	if o != nil && !IsNil(o.AnchorPath) {
		return true
	}

	return false
}

// SetAnchorPath gets a reference to the given string and assigns it to the AnchorPath field.
func (o *FileAnchorCandidate) SetAnchorPath(v string) {
	o.AnchorPath = &v
}

// GetDir returns the Dir field value if set, zero value otherwise.
func (o *FileAnchorCandidate) GetDir() string {
	if o == nil || IsNil(o.Dir) {
		var ret string
		return ret
	}
	return *o.Dir
}

// GetDirOk returns a tuple with the Dir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileAnchorCandidate) GetDirOk() (*string, bool) {
	if o == nil || IsNil(o.Dir) {
		return nil, false
	}
	return o.Dir, true
}

// HasDir returns a boolean if a field has been set.
func (o *FileAnchorCandidate) HasDir() bool {
	if o != nil && !IsNil(o.Dir) {
		return true
	}

	return false
}

// SetDir gets a reference to the given string and assigns it to the Dir field.
func (o *FileAnchorCandidate) SetDir(v string) {
	o.Dir = &v
}

// GetExact returns the Exact field value if set, zero value otherwise.
func (o *FileAnchorCandidate) GetExact() bool {
	if o == nil || IsNil(o.Exact) {
		var ret bool
		return ret
	}
	return *o.Exact
}

// GetExactOk returns a tuple with the Exact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileAnchorCandidate) GetExactOk() (*bool, bool) {
	if o == nil || IsNil(o.Exact) {
		return nil, false
	}
	return o.Exact, true
}

// HasExact returns a boolean if a field has been set.
func (o *FileAnchorCandidate) HasExact() bool {
	if o != nil && !IsNil(o.Exact) {
		return true
	}

	return false
}

// SetExact gets a reference to the given bool and assigns it to the Exact field.
func (o *FileAnchorCandidate) SetExact(v bool) {
	o.Exact = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *FileAnchorCandidate) GetConfidence() float64 {
	if o == nil || IsNil(o.Confidence) {
		var ret float64
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileAnchorCandidate) GetConfidenceOk() (*float64, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *FileAnchorCandidate) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given float64 and assigns it to the Confidence field.
func (o *FileAnchorCandidate) SetConfidence(v float64) {
	o.Confidence = &v
}

func (o FileAnchorCandidate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileAnchorCandidate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequirementId) {
		toSerialize["requirementId"] = o.RequirementId
	}
	if !IsNil(o.RequirementSeq) {
		toSerialize["requirementSeq"] = o.RequirementSeq
	}
	if !IsNil(o.RequirementTitle) {
		toSerialize["requirementTitle"] = o.RequirementTitle
	}
	if !IsNil(o.TestId) {
		toSerialize["testId"] = o.TestId
	}
	if !IsNil(o.TestSeq) {
		toSerialize["testSeq"] = o.TestSeq
	}
	if !IsNil(o.TestTitle) {
		toSerialize["testTitle"] = o.TestTitle
	}
	if !IsNil(o.TestFilePath) {
		toSerialize["testFilePath"] = o.TestFilePath
	}
	if !IsNil(o.AnchorPath) {
		toSerialize["anchorPath"] = o.AnchorPath
	}
	if !IsNil(o.Dir) {
		toSerialize["dir"] = o.Dir
	}
	if !IsNil(o.Exact) {
		toSerialize["exact"] = o.Exact
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	return toSerialize, nil
}

type NullableFileAnchorCandidate struct {
	value *FileAnchorCandidate
	isSet bool
}

func (v NullableFileAnchorCandidate) Get() *FileAnchorCandidate {
	return v.value
}

func (v *NullableFileAnchorCandidate) Set(val *FileAnchorCandidate) {
	v.value = val
	v.isSet = true
}

func (v NullableFileAnchorCandidate) IsSet() bool {
	return v.isSet
}

func (v *NullableFileAnchorCandidate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileAnchorCandidate(val *FileAnchorCandidate) *NullableFileAnchorCandidate {
	return &NullableFileAnchorCandidate{value: val, isSet: true}
}

func (v NullableFileAnchorCandidate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileAnchorCandidate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


