/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the ProductWithSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductWithSummary{}

// ProductWithSummary struct for ProductWithSummary
type ProductWithSummary struct {
	Product *Product `json:"product,omitempty"`
	Summary *ProductListSummary `json:"summary,omitempty"`
}

// NewProductWithSummary instantiates a new ProductWithSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductWithSummary() *ProductWithSummary {
	this := ProductWithSummary{}
	return &this
}

// NewProductWithSummaryWithDefaults instantiates a new ProductWithSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductWithSummaryWithDefaults() *ProductWithSummary {
	this := ProductWithSummary{}
	return &this
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *ProductWithSummary) GetProduct() Product {
	if o == nil || IsNil(o.Product) {
		var ret Product
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductWithSummary) GetProductOk() (*Product, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *ProductWithSummary) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given Product and assigns it to the Product field.
func (o *ProductWithSummary) SetProduct(v Product) {
	o.Product = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *ProductWithSummary) GetSummary() ProductListSummary {
	if o == nil || IsNil(o.Summary) {
		var ret ProductListSummary
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductWithSummary) GetSummaryOk() (*ProductListSummary, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *ProductWithSummary) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given ProductListSummary and assigns it to the Summary field.
func (o *ProductWithSummary) SetSummary(v ProductListSummary) {
	o.Summary = &v
}

func (o ProductWithSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductWithSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableProductWithSummary struct {
	value *ProductWithSummary
	isSet bool
}

func (v NullableProductWithSummary) Get() *ProductWithSummary {
	return v.value
}

func (v *NullableProductWithSummary) Set(val *ProductWithSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableProductWithSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableProductWithSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductWithSummary(val *ProductWithSummary) *NullableProductWithSummary {
	return &NullableProductWithSummary{value: val, isSet: true}
}

func (v NullableProductWithSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductWithSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


