/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
	"fmt"
)

// VerdictStatus the model 'VerdictStatus'
type VerdictStatus string

// List of VerdictStatus
const (
	VERDICT_STATUS_UNSPECIFIED VerdictStatus = "VERDICT_STATUS_UNSPECIFIED"
	VERDICT_STATUS_PASS VerdictStatus = "VERDICT_STATUS_PASS"
	VERDICT_STATUS_BLOCKED VerdictStatus = "VERDICT_STATUS_BLOCKED"
	VERDICT_STATUS_RISK_ACCEPTED VerdictStatus = "VERDICT_STATUS_RISK_ACCEPTED"
)

// All allowed values of VerdictStatus enum
var AllowedVerdictStatusEnumValues = []VerdictStatus{
	"VERDICT_STATUS_UNSPECIFIED",
	"VERDICT_STATUS_PASS",
	"VERDICT_STATUS_BLOCKED",
	"VERDICT_STATUS_RISK_ACCEPTED",
}

func (v *VerdictStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VerdictStatus(value)
	for _, existing := range AllowedVerdictStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VerdictStatus", value)
}

// NewVerdictStatusFromValue returns a pointer to a valid VerdictStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVerdictStatusFromValue(v string) (*VerdictStatus, error) {
	ev := VerdictStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for VerdictStatus: valid values are %v", v, AllowedVerdictStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VerdictStatus) IsValid() bool {
	for _, existing := range AllowedVerdictStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to VerdictStatus value
func (v VerdictStatus) Ptr() *VerdictStatus {
	return &v
}

type NullableVerdictStatus struct {
	value *VerdictStatus
	isSet bool
}

func (v NullableVerdictStatus) Get() *VerdictStatus {
	return v.value
}

func (v *NullableVerdictStatus) Set(val *VerdictStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableVerdictStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableVerdictStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerdictStatus(val *VerdictStatus) *NullableVerdictStatus {
	return &NullableVerdictStatus{value: val, isSet: true}
}

func (v NullableVerdictStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerdictStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

