/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
	"time"
)

// checks if the CoverageGap type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoverageGap{}

// CoverageGap CoverageGap is one under-covered requirement with its coverage counters, the reason for its status, and the signals that ranked it.
type CoverageGap struct {
	Requirement *Requirement `json:"requirement,omitempty"`
	CoverageStatus *string `json:"coverageStatus,omitempty"`
	LinkedTestCount *int32 `json:"linkedTestCount,omitempty"`
	ProposedTestCount *int32 `json:"proposedTestCount,omitempty"`
	StaleTestCount *int32 `json:"staleTestCount,omitempty"`
	CoverageItemCount *int32 `json:"coverageItemCount,omitempty"`
	LastTestUpdatedAt *time.Time `json:"lastTestUpdatedAt,omitempty"`
	CoverageStatusReason *string `json:"coverageStatusReason,omitempty"`
	RankingSignals []string `json:"rankingSignals,omitempty"`
	// Prior intent sessions' JUDGEMENTS on this requirement's missing verification: risk acceptances that priced it, and test deferrals that handed the missing test to a next session. Both are read from the close artifacts recorded on session drafts, matched by main twin. They are next- session input (\"someone already looked at this\"), not coverage — neither moves coverage_status.  Read them with these four properties in mind, because none of them are obvious from the names:   - They count ARTIFACT ROWS, not sessions. One session that accepts under     two criteria naming this requirement contributes 2, and two sessions     that each accept it once also contribute 2.   - Nothing marks a judgement resolved. A deferral of a requirement that     has since been covered still counts, and a risk acceptance survives the     condition it was signed against.   - A judgement from an intent branch that was ABANDONED and never merged     counts exactly like one that landed: the artifacts live on the session     draft, and an unmerged draft is still a requirement. \"Someone already     priced this\" can therefore refer to a decision that never shipped.   - 0 means nobody judged it — not that nobody could.  Deliberately NOT folded into proposed_test_count (field 4): that one is derived from branch test-link proposals and is not writable from a close.
	RiskAcceptedCount *int32 `json:"riskAcceptedCount,omitempty"`
	DeferredTestCount *int32 `json:"deferredTestCount,omitempty"`
}

// NewCoverageGap instantiates a new CoverageGap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoverageGap() *CoverageGap {
	this := CoverageGap{}
	return &this
}

// NewCoverageGapWithDefaults instantiates a new CoverageGap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoverageGapWithDefaults() *CoverageGap {
	this := CoverageGap{}
	return &this
}

// GetRequirement returns the Requirement field value if set, zero value otherwise.
func (o *CoverageGap) GetRequirement() Requirement {
	if o == nil || IsNil(o.Requirement) {
		var ret Requirement
		return ret
	}
	return *o.Requirement
}

// GetRequirementOk returns a tuple with the Requirement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverageGap) GetRequirementOk() (*Requirement, bool) {
	if o == nil || IsNil(o.Requirement) {
		return nil, false
	}
	return o.Requirement, true
}

// HasRequirement returns a boolean if a field has been set.
func (o *CoverageGap) HasRequirement() bool {
	if o != nil && !IsNil(o.Requirement) {
		return true
	}

	return false
}

// SetRequirement gets a reference to the given Requirement and assigns it to the Requirement field.
func (o *CoverageGap) SetRequirement(v Requirement) {
	o.Requirement = &v
}

// GetCoverageStatus returns the CoverageStatus field value if set, zero value otherwise.
func (o *CoverageGap) GetCoverageStatus() string {
	if o == nil || IsNil(o.CoverageStatus) {
		var ret string
		return ret
	}
	return *o.CoverageStatus
}

// GetCoverageStatusOk returns a tuple with the CoverageStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverageGap) GetCoverageStatusOk() (*string, bool) {
	if o == nil || IsNil(o.CoverageStatus) {
		return nil, false
	}
	return o.CoverageStatus, true
}

// HasCoverageStatus returns a boolean if a field has been set.
func (o *CoverageGap) HasCoverageStatus() bool {
	if o != nil && !IsNil(o.CoverageStatus) {
		return true
	}

	return false
}

// SetCoverageStatus gets a reference to the given string and assigns it to the CoverageStatus field.
func (o *CoverageGap) SetCoverageStatus(v string) {
	o.CoverageStatus = &v
}

// GetLinkedTestCount returns the LinkedTestCount field value if set, zero value otherwise.
func (o *CoverageGap) GetLinkedTestCount() int32 {
	if o == nil || IsNil(o.LinkedTestCount) {
		var ret int32
		return ret
	}
	return *o.LinkedTestCount
}

// GetLinkedTestCountOk returns a tuple with the LinkedTestCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverageGap) GetLinkedTestCountOk() (*int32, bool) {
	if o == nil || IsNil(o.LinkedTestCount) {
		return nil, false
	}
	return o.LinkedTestCount, true
}

// HasLinkedTestCount returns a boolean if a field has been set.
func (o *CoverageGap) HasLinkedTestCount() bool {
	if o != nil && !IsNil(o.LinkedTestCount) {
		return true
	}

	return false
}

// SetLinkedTestCount gets a reference to the given int32 and assigns it to the LinkedTestCount field.
func (o *CoverageGap) SetLinkedTestCount(v int32) {
	o.LinkedTestCount = &v
}

// GetProposedTestCount returns the ProposedTestCount field value if set, zero value otherwise.
func (o *CoverageGap) GetProposedTestCount() int32 {
	if o == nil || IsNil(o.ProposedTestCount) {
		var ret int32
		return ret
	}
	return *o.ProposedTestCount
}

// GetProposedTestCountOk returns a tuple with the ProposedTestCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverageGap) GetProposedTestCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ProposedTestCount) {
		return nil, false
	}
	return o.ProposedTestCount, true
}

// HasProposedTestCount returns a boolean if a field has been set.
func (o *CoverageGap) HasProposedTestCount() bool {
	if o != nil && !IsNil(o.ProposedTestCount) {
		return true
	}

	return false
}

// SetProposedTestCount gets a reference to the given int32 and assigns it to the ProposedTestCount field.
func (o *CoverageGap) SetProposedTestCount(v int32) {
	o.ProposedTestCount = &v
}

// GetStaleTestCount returns the StaleTestCount field value if set, zero value otherwise.
func (o *CoverageGap) GetStaleTestCount() int32 {
	if o == nil || IsNil(o.StaleTestCount) {
		var ret int32
		return ret
	}
	return *o.StaleTestCount
}

// GetStaleTestCountOk returns a tuple with the StaleTestCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverageGap) GetStaleTestCountOk() (*int32, bool) {
	if o == nil || IsNil(o.StaleTestCount) {
		return nil, false
	}
	return o.StaleTestCount, true
}

// HasStaleTestCount returns a boolean if a field has been set.
func (o *CoverageGap) HasStaleTestCount() bool {
	if o != nil && !IsNil(o.StaleTestCount) {
		return true
	}

	return false
}

// SetStaleTestCount gets a reference to the given int32 and assigns it to the StaleTestCount field.
func (o *CoverageGap) SetStaleTestCount(v int32) {
	o.StaleTestCount = &v
}

// GetCoverageItemCount returns the CoverageItemCount field value if set, zero value otherwise.
func (o *CoverageGap) GetCoverageItemCount() int32 {
	if o == nil || IsNil(o.CoverageItemCount) {
		var ret int32
		return ret
	}
	return *o.CoverageItemCount
}

// GetCoverageItemCountOk returns a tuple with the CoverageItemCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverageGap) GetCoverageItemCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CoverageItemCount) {
		return nil, false
	}
	return o.CoverageItemCount, true
}

// HasCoverageItemCount returns a boolean if a field has been set.
func (o *CoverageGap) HasCoverageItemCount() bool {
	if o != nil && !IsNil(o.CoverageItemCount) {
		return true
	}

	return false
}

// SetCoverageItemCount gets a reference to the given int32 and assigns it to the CoverageItemCount field.
func (o *CoverageGap) SetCoverageItemCount(v int32) {
	o.CoverageItemCount = &v
}

// GetLastTestUpdatedAt returns the LastTestUpdatedAt field value if set, zero value otherwise.
func (o *CoverageGap) GetLastTestUpdatedAt() time.Time {
	if o == nil || IsNil(o.LastTestUpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastTestUpdatedAt
}

// GetLastTestUpdatedAtOk returns a tuple with the LastTestUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverageGap) GetLastTestUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastTestUpdatedAt) {
		return nil, false
	}
	return o.LastTestUpdatedAt, true
}

// HasLastTestUpdatedAt returns a boolean if a field has been set.
func (o *CoverageGap) HasLastTestUpdatedAt() bool {
	if o != nil && !IsNil(o.LastTestUpdatedAt) {
		return true
	}

	return false
}

// SetLastTestUpdatedAt gets a reference to the given time.Time and assigns it to the LastTestUpdatedAt field.
func (o *CoverageGap) SetLastTestUpdatedAt(v time.Time) {
	o.LastTestUpdatedAt = &v
}

// GetCoverageStatusReason returns the CoverageStatusReason field value if set, zero value otherwise.
func (o *CoverageGap) GetCoverageStatusReason() string {
	if o == nil || IsNil(o.CoverageStatusReason) {
		var ret string
		return ret
	}
	return *o.CoverageStatusReason
}

// GetCoverageStatusReasonOk returns a tuple with the CoverageStatusReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverageGap) GetCoverageStatusReasonOk() (*string, bool) {
	if o == nil || IsNil(o.CoverageStatusReason) {
		return nil, false
	}
	return o.CoverageStatusReason, true
}

// HasCoverageStatusReason returns a boolean if a field has been set.
func (o *CoverageGap) HasCoverageStatusReason() bool {
	if o != nil && !IsNil(o.CoverageStatusReason) {
		return true
	}

	return false
}

// SetCoverageStatusReason gets a reference to the given string and assigns it to the CoverageStatusReason field.
func (o *CoverageGap) SetCoverageStatusReason(v string) {
	o.CoverageStatusReason = &v
}

// GetRankingSignals returns the RankingSignals field value if set, zero value otherwise.
func (o *CoverageGap) GetRankingSignals() []string {
	if o == nil || IsNil(o.RankingSignals) {
		var ret []string
		return ret
	}
	return o.RankingSignals
}

// GetRankingSignalsOk returns a tuple with the RankingSignals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverageGap) GetRankingSignalsOk() ([]string, bool) {
	if o == nil || IsNil(o.RankingSignals) {
		return nil, false
	}
	return o.RankingSignals, true
}

// HasRankingSignals returns a boolean if a field has been set.
func (o *CoverageGap) HasRankingSignals() bool {
	if o != nil && !IsNil(o.RankingSignals) {
		return true
	}

	return false
}

// SetRankingSignals gets a reference to the given []string and assigns it to the RankingSignals field.
func (o *CoverageGap) SetRankingSignals(v []string) {
	o.RankingSignals = v
}

// GetRiskAcceptedCount returns the RiskAcceptedCount field value if set, zero value otherwise.
func (o *CoverageGap) GetRiskAcceptedCount() int32 {
	if o == nil || IsNil(o.RiskAcceptedCount) {
		var ret int32
		return ret
	}
	return *o.RiskAcceptedCount
}

// GetRiskAcceptedCountOk returns a tuple with the RiskAcceptedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverageGap) GetRiskAcceptedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RiskAcceptedCount) {
		return nil, false
	}
	return o.RiskAcceptedCount, true
}

// HasRiskAcceptedCount returns a boolean if a field has been set.
func (o *CoverageGap) HasRiskAcceptedCount() bool {
	if o != nil && !IsNil(o.RiskAcceptedCount) {
		return true
	}

	return false
}

// SetRiskAcceptedCount gets a reference to the given int32 and assigns it to the RiskAcceptedCount field.
func (o *CoverageGap) SetRiskAcceptedCount(v int32) {
	o.RiskAcceptedCount = &v
}

// GetDeferredTestCount returns the DeferredTestCount field value if set, zero value otherwise.
func (o *CoverageGap) GetDeferredTestCount() int32 {
	if o == nil || IsNil(o.DeferredTestCount) {
		var ret int32
		return ret
	}
	return *o.DeferredTestCount
}

// GetDeferredTestCountOk returns a tuple with the DeferredTestCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverageGap) GetDeferredTestCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DeferredTestCount) {
		return nil, false
	}
	return o.DeferredTestCount, true
}

// HasDeferredTestCount returns a boolean if a field has been set.
func (o *CoverageGap) HasDeferredTestCount() bool {
	if o != nil && !IsNil(o.DeferredTestCount) {
		return true
	}

	return false
}

// SetDeferredTestCount gets a reference to the given int32 and assigns it to the DeferredTestCount field.
func (o *CoverageGap) SetDeferredTestCount(v int32) {
	o.DeferredTestCount = &v
}

func (o CoverageGap) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoverageGap) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Requirement) {
		toSerialize["requirement"] = o.Requirement
	}
	if !IsNil(o.CoverageStatus) {
		toSerialize["coverageStatus"] = o.CoverageStatus
	}
	if !IsNil(o.LinkedTestCount) {
		toSerialize["linkedTestCount"] = o.LinkedTestCount
	}
	if !IsNil(o.ProposedTestCount) {
		toSerialize["proposedTestCount"] = o.ProposedTestCount
	}
	if !IsNil(o.StaleTestCount) {
		toSerialize["staleTestCount"] = o.StaleTestCount
	}
	if !IsNil(o.CoverageItemCount) {
		toSerialize["coverageItemCount"] = o.CoverageItemCount
	}
	if !IsNil(o.LastTestUpdatedAt) {
		toSerialize["lastTestUpdatedAt"] = o.LastTestUpdatedAt
	}
	if !IsNil(o.CoverageStatusReason) {
		toSerialize["coverageStatusReason"] = o.CoverageStatusReason
	}
	if !IsNil(o.RankingSignals) {
		toSerialize["rankingSignals"] = o.RankingSignals
	}
	if !IsNil(o.RiskAcceptedCount) {
		toSerialize["riskAcceptedCount"] = o.RiskAcceptedCount
	}
	if !IsNil(o.DeferredTestCount) {
		toSerialize["deferredTestCount"] = o.DeferredTestCount
	}
	return toSerialize, nil
}

type NullableCoverageGap struct {
	value *CoverageGap
	isSet bool
}

func (v NullableCoverageGap) Get() *CoverageGap {
	return v.value
}

func (v *NullableCoverageGap) Set(val *CoverageGap) {
	v.value = val
	v.isSet = true
}

func (v NullableCoverageGap) IsSet() bool {
	return v.isSet
}

func (v *NullableCoverageGap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoverageGap(val *CoverageGap) *NullableCoverageGap {
	return &NullableCoverageGap{value: val, isSet: true}
}

func (v NullableCoverageGap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoverageGap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


