/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the CreateEnvironmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEnvironmentResponse{}

// CreateEnvironmentResponse struct for CreateEnvironmentResponse
type CreateEnvironmentResponse struct {
	Environment *Environment `json:"environment,omitempty"`
}

// NewCreateEnvironmentResponse instantiates a new CreateEnvironmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEnvironmentResponse() *CreateEnvironmentResponse {
	this := CreateEnvironmentResponse{}
	return &this
}

// NewCreateEnvironmentResponseWithDefaults instantiates a new CreateEnvironmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEnvironmentResponseWithDefaults() *CreateEnvironmentResponse {
	this := CreateEnvironmentResponse{}
	return &this
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *CreateEnvironmentResponse) GetEnvironment() Environment {
	if o == nil || IsNil(o.Environment) {
		var ret Environment
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentResponse) GetEnvironmentOk() (*Environment, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *CreateEnvironmentResponse) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given Environment and assigns it to the Environment field.
func (o *CreateEnvironmentResponse) SetEnvironment(v Environment) {
	o.Environment = &v
}

func (o CreateEnvironmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEnvironmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	return toSerialize, nil
}

type NullableCreateEnvironmentResponse struct {
	value *CreateEnvironmentResponse
	isSet bool
}

func (v NullableCreateEnvironmentResponse) Get() *CreateEnvironmentResponse {
	return v.value
}

func (v *NullableCreateEnvironmentResponse) Set(val *CreateEnvironmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEnvironmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEnvironmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEnvironmentResponse(val *CreateEnvironmentResponse) *NullableCreateEnvironmentResponse {
	return &NullableCreateEnvironmentResponse{value: val, isSet: true}
}

func (v NullableCreateEnvironmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEnvironmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


