/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the ListBranchCodeLinksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListBranchCodeLinksResponse{}

// ListBranchCodeLinksResponse struct for ListBranchCodeLinksResponse
type ListBranchCodeLinksResponse struct {
	CodeLinks []CodeLink `json:"codeLinks,omitempty"`
}

// NewListBranchCodeLinksResponse instantiates a new ListBranchCodeLinksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBranchCodeLinksResponse() *ListBranchCodeLinksResponse {
	this := ListBranchCodeLinksResponse{}
	return &this
}

// NewListBranchCodeLinksResponseWithDefaults instantiates a new ListBranchCodeLinksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBranchCodeLinksResponseWithDefaults() *ListBranchCodeLinksResponse {
	this := ListBranchCodeLinksResponse{}
	return &this
}

// GetCodeLinks returns the CodeLinks field value if set, zero value otherwise.
func (o *ListBranchCodeLinksResponse) GetCodeLinks() []CodeLink {
	if o == nil || IsNil(o.CodeLinks) {
		var ret []CodeLink
		return ret
	}
	return o.CodeLinks
}

// GetCodeLinksOk returns a tuple with the CodeLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBranchCodeLinksResponse) GetCodeLinksOk() ([]CodeLink, bool) {
	if o == nil || IsNil(o.CodeLinks) {
		return nil, false
	}
	return o.CodeLinks, true
}

// HasCodeLinks returns a boolean if a field has been set.
func (o *ListBranchCodeLinksResponse) HasCodeLinks() bool {
	if o != nil && !IsNil(o.CodeLinks) {
		return true
	}

	return false
}

// SetCodeLinks gets a reference to the given []CodeLink and assigns it to the CodeLinks field.
func (o *ListBranchCodeLinksResponse) SetCodeLinks(v []CodeLink) {
	o.CodeLinks = v
}

func (o ListBranchCodeLinksResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListBranchCodeLinksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CodeLinks) {
		toSerialize["codeLinks"] = o.CodeLinks
	}
	return toSerialize, nil
}

type NullableListBranchCodeLinksResponse struct {
	value *ListBranchCodeLinksResponse
	isSet bool
}

func (v NullableListBranchCodeLinksResponse) Get() *ListBranchCodeLinksResponse {
	return v.value
}

func (v *NullableListBranchCodeLinksResponse) Set(val *ListBranchCodeLinksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListBranchCodeLinksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListBranchCodeLinksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBranchCodeLinksResponse(val *ListBranchCodeLinksResponse) *NullableListBranchCodeLinksResponse {
	return &NullableListBranchCodeLinksResponse{value: val, isSet: true}
}

func (v NullableListBranchCodeLinksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBranchCodeLinksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


