/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the WriteRequirementEdgeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WriteRequirementEdgeResponse{}

// WriteRequirementEdgeResponse struct for WriteRequirementEdgeResponse
type WriteRequirementEdgeResponse struct {
	EdgeId *string `json:"edgeId,omitempty"`
}

// NewWriteRequirementEdgeResponse instantiates a new WriteRequirementEdgeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWriteRequirementEdgeResponse() *WriteRequirementEdgeResponse {
	this := WriteRequirementEdgeResponse{}
	return &this
}

// NewWriteRequirementEdgeResponseWithDefaults instantiates a new WriteRequirementEdgeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWriteRequirementEdgeResponseWithDefaults() *WriteRequirementEdgeResponse {
	this := WriteRequirementEdgeResponse{}
	return &this
}

// GetEdgeId returns the EdgeId field value if set, zero value otherwise.
func (o *WriteRequirementEdgeResponse) GetEdgeId() string {
	if o == nil || IsNil(o.EdgeId) {
		var ret string
		return ret
	}
	return *o.EdgeId
}

// GetEdgeIdOk returns a tuple with the EdgeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WriteRequirementEdgeResponse) GetEdgeIdOk() (*string, bool) {
	if o == nil || IsNil(o.EdgeId) {
		return nil, false
	}
	return o.EdgeId, true
}

// HasEdgeId returns a boolean if a field has been set.
func (o *WriteRequirementEdgeResponse) HasEdgeId() bool {
	if o != nil && !IsNil(o.EdgeId) {
		return true
	}

	return false
}

// SetEdgeId gets a reference to the given string and assigns it to the EdgeId field.
func (o *WriteRequirementEdgeResponse) SetEdgeId(v string) {
	o.EdgeId = &v
}

func (o WriteRequirementEdgeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WriteRequirementEdgeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EdgeId) {
		toSerialize["edgeId"] = o.EdgeId
	}
	return toSerialize, nil
}

type NullableWriteRequirementEdgeResponse struct {
	value *WriteRequirementEdgeResponse
	isSet bool
}

func (v NullableWriteRequirementEdgeResponse) Get() *WriteRequirementEdgeResponse {
	return v.value
}

func (v *NullableWriteRequirementEdgeResponse) Set(val *WriteRequirementEdgeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWriteRequirementEdgeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWriteRequirementEdgeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWriteRequirementEdgeResponse(val *WriteRequirementEdgeResponse) *NullableWriteRequirementEdgeResponse {
	return &NullableWriteRequirementEdgeResponse{value: val, isSet: true}
}

func (v NullableWriteRequirementEdgeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWriteRequirementEdgeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


