/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the DeclareRequirementEdgeIntentBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeclareRequirementEdgeIntentBody{}

// DeclareRequirementEdgeIntentBody DeclareRequirementEdgeIntent records a deferred semantic edge for a brand-new feature whose endpoint(s) are not yet on main. The intent is stored on the branch and materialized into a real edge when the branch merges to main.
type DeclareRequirementEdgeIntentBody struct {
	// branch is the branch the intent is declared on (empty = main).
	Branch *string `json:"branch,omitempty"`
	SrcRequirementId *string `json:"srcRequirementId,omitempty"`
	// Exactly one dst endpoint (see WriteRequirementEdgeRequest). dst_requirement_id may be empty when dst_component_id is set.
	DstRequirementId *string `json:"dstRequirementId,omitempty"`
	// edge_type must be \"depends_on\"/\"traces_to\" (req→req) or \"impacts_component\" (req→component).
	EdgeType *string `json:"edgeType,omitempty"`
	// confidence must be provided; explicit 0.0 is valid, omitted is not.
	Confidence *float64 `json:"confidence,omitempty"`
	Rationale *string `json:"rationale,omitempty"`
	// dst_component_id sets a req→component endpoint (shift-left v3). Mutually exclusive with dst_requirement_id.
	DstComponentId *string `json:"dstComponentId,omitempty"`
}

// NewDeclareRequirementEdgeIntentBody instantiates a new DeclareRequirementEdgeIntentBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeclareRequirementEdgeIntentBody() *DeclareRequirementEdgeIntentBody {
	this := DeclareRequirementEdgeIntentBody{}
	return &this
}

// NewDeclareRequirementEdgeIntentBodyWithDefaults instantiates a new DeclareRequirementEdgeIntentBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeclareRequirementEdgeIntentBodyWithDefaults() *DeclareRequirementEdgeIntentBody {
	this := DeclareRequirementEdgeIntentBody{}
	return &this
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *DeclareRequirementEdgeIntentBody) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareRequirementEdgeIntentBody) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *DeclareRequirementEdgeIntentBody) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *DeclareRequirementEdgeIntentBody) SetBranch(v string) {
	o.Branch = &v
}

// GetSrcRequirementId returns the SrcRequirementId field value if set, zero value otherwise.
func (o *DeclareRequirementEdgeIntentBody) GetSrcRequirementId() string {
	if o == nil || IsNil(o.SrcRequirementId) {
		var ret string
		return ret
	}
	return *o.SrcRequirementId
}

// GetSrcRequirementIdOk returns a tuple with the SrcRequirementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareRequirementEdgeIntentBody) GetSrcRequirementIdOk() (*string, bool) {
	if o == nil || IsNil(o.SrcRequirementId) {
		return nil, false
	}
	return o.SrcRequirementId, true
}

// HasSrcRequirementId returns a boolean if a field has been set.
func (o *DeclareRequirementEdgeIntentBody) HasSrcRequirementId() bool {
	if o != nil && !IsNil(o.SrcRequirementId) {
		return true
	}

	return false
}

// SetSrcRequirementId gets a reference to the given string and assigns it to the SrcRequirementId field.
func (o *DeclareRequirementEdgeIntentBody) SetSrcRequirementId(v string) {
	o.SrcRequirementId = &v
}

// GetDstRequirementId returns the DstRequirementId field value if set, zero value otherwise.
func (o *DeclareRequirementEdgeIntentBody) GetDstRequirementId() string {
	if o == nil || IsNil(o.DstRequirementId) {
		var ret string
		return ret
	}
	return *o.DstRequirementId
}

// GetDstRequirementIdOk returns a tuple with the DstRequirementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareRequirementEdgeIntentBody) GetDstRequirementIdOk() (*string, bool) {
	if o == nil || IsNil(o.DstRequirementId) {
		return nil, false
	}
	return o.DstRequirementId, true
}

// HasDstRequirementId returns a boolean if a field has been set.
func (o *DeclareRequirementEdgeIntentBody) HasDstRequirementId() bool {
	if o != nil && !IsNil(o.DstRequirementId) {
		return true
	}

	return false
}

// SetDstRequirementId gets a reference to the given string and assigns it to the DstRequirementId field.
func (o *DeclareRequirementEdgeIntentBody) SetDstRequirementId(v string) {
	o.DstRequirementId = &v
}

// GetEdgeType returns the EdgeType field value if set, zero value otherwise.
func (o *DeclareRequirementEdgeIntentBody) GetEdgeType() string {
	if o == nil || IsNil(o.EdgeType) {
		var ret string
		return ret
	}
	return *o.EdgeType
}

// GetEdgeTypeOk returns a tuple with the EdgeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareRequirementEdgeIntentBody) GetEdgeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EdgeType) {
		return nil, false
	}
	return o.EdgeType, true
}

// HasEdgeType returns a boolean if a field has been set.
func (o *DeclareRequirementEdgeIntentBody) HasEdgeType() bool {
	if o != nil && !IsNil(o.EdgeType) {
		return true
	}

	return false
}

// SetEdgeType gets a reference to the given string and assigns it to the EdgeType field.
func (o *DeclareRequirementEdgeIntentBody) SetEdgeType(v string) {
	o.EdgeType = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *DeclareRequirementEdgeIntentBody) GetConfidence() float64 {
	if o == nil || IsNil(o.Confidence) {
		var ret float64
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareRequirementEdgeIntentBody) GetConfidenceOk() (*float64, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *DeclareRequirementEdgeIntentBody) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given float64 and assigns it to the Confidence field.
func (o *DeclareRequirementEdgeIntentBody) SetConfidence(v float64) {
	o.Confidence = &v
}

// GetRationale returns the Rationale field value if set, zero value otherwise.
func (o *DeclareRequirementEdgeIntentBody) GetRationale() string {
	if o == nil || IsNil(o.Rationale) {
		var ret string
		return ret
	}
	return *o.Rationale
}

// GetRationaleOk returns a tuple with the Rationale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareRequirementEdgeIntentBody) GetRationaleOk() (*string, bool) {
	if o == nil || IsNil(o.Rationale) {
		return nil, false
	}
	return o.Rationale, true
}

// HasRationale returns a boolean if a field has been set.
func (o *DeclareRequirementEdgeIntentBody) HasRationale() bool {
	if o != nil && !IsNil(o.Rationale) {
		return true
	}

	return false
}

// SetRationale gets a reference to the given string and assigns it to the Rationale field.
func (o *DeclareRequirementEdgeIntentBody) SetRationale(v string) {
	o.Rationale = &v
}

// GetDstComponentId returns the DstComponentId field value if set, zero value otherwise.
func (o *DeclareRequirementEdgeIntentBody) GetDstComponentId() string {
	if o == nil || IsNil(o.DstComponentId) {
		var ret string
		return ret
	}
	return *o.DstComponentId
}

// GetDstComponentIdOk returns a tuple with the DstComponentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeclareRequirementEdgeIntentBody) GetDstComponentIdOk() (*string, bool) {
	if o == nil || IsNil(o.DstComponentId) {
		return nil, false
	}
	return o.DstComponentId, true
}

// HasDstComponentId returns a boolean if a field has been set.
func (o *DeclareRequirementEdgeIntentBody) HasDstComponentId() bool {
	if o != nil && !IsNil(o.DstComponentId) {
		return true
	}

	return false
}

// SetDstComponentId gets a reference to the given string and assigns it to the DstComponentId field.
func (o *DeclareRequirementEdgeIntentBody) SetDstComponentId(v string) {
	o.DstComponentId = &v
}

func (o DeclareRequirementEdgeIntentBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeclareRequirementEdgeIntentBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.SrcRequirementId) {
		toSerialize["srcRequirementId"] = o.SrcRequirementId
	}
	if !IsNil(o.DstRequirementId) {
		toSerialize["dstRequirementId"] = o.DstRequirementId
	}
	if !IsNil(o.EdgeType) {
		toSerialize["edgeType"] = o.EdgeType
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.Rationale) {
		toSerialize["rationale"] = o.Rationale
	}
	if !IsNil(o.DstComponentId) {
		toSerialize["dstComponentId"] = o.DstComponentId
	}
	return toSerialize, nil
}

type NullableDeclareRequirementEdgeIntentBody struct {
	value *DeclareRequirementEdgeIntentBody
	isSet bool
}

func (v NullableDeclareRequirementEdgeIntentBody) Get() *DeclareRequirementEdgeIntentBody {
	return v.value
}

func (v *NullableDeclareRequirementEdgeIntentBody) Set(val *DeclareRequirementEdgeIntentBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDeclareRequirementEdgeIntentBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDeclareRequirementEdgeIntentBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeclareRequirementEdgeIntentBody(val *DeclareRequirementEdgeIntentBody) *NullableDeclareRequirementEdgeIntentBody {
	return &NullableDeclareRequirementEdgeIntentBody{value: val, isSet: true}
}

func (v NullableDeclareRequirementEdgeIntentBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeclareRequirementEdgeIntentBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


