/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the FixHint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FixHint{}

// FixHint struct for FixHint
type FixHint struct {
	Component *string `json:"component,omitempty"`
	Action *string `json:"action,omitempty"`
}

// NewFixHint instantiates a new FixHint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFixHint() *FixHint {
	this := FixHint{}
	return &this
}

// NewFixHintWithDefaults instantiates a new FixHint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFixHintWithDefaults() *FixHint {
	this := FixHint{}
	return &this
}

// GetComponent returns the Component field value if set, zero value otherwise.
func (o *FixHint) GetComponent() string {
	if o == nil || IsNil(o.Component) {
		var ret string
		return ret
	}
	return *o.Component
}

// GetComponentOk returns a tuple with the Component field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FixHint) GetComponentOk() (*string, bool) {
	if o == nil || IsNil(o.Component) {
		return nil, false
	}
	return o.Component, true
}

// HasComponent returns a boolean if a field has been set.
func (o *FixHint) HasComponent() bool {
	if o != nil && !IsNil(o.Component) {
		return true
	}

	return false
}

// SetComponent gets a reference to the given string and assigns it to the Component field.
func (o *FixHint) SetComponent(v string) {
	o.Component = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *FixHint) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FixHint) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *FixHint) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *FixHint) SetAction(v string) {
	o.Action = &v
}

func (o FixHint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FixHint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Component) {
		toSerialize["component"] = o.Component
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	return toSerialize, nil
}

type NullableFixHint struct {
	value *FixHint
	isSet bool
}

func (v NullableFixHint) Get() *FixHint {
	return v.value
}

func (v *NullableFixHint) Set(val *FixHint) {
	v.value = val
	v.isSet = true
}

func (v NullableFixHint) IsSet() bool {
	return v.isSet
}

func (v *NullableFixHint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFixHint(val *FixHint) *NullableFixHint {
	return &NullableFixHint{value: val, isSet: true}
}

func (v NullableFixHint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFixHint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


