/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
	"time"
)

// checks if the Component type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Component{}

// Component Component is a deployment/architectural unit of a product. The repository/component_paths/repository_aliases scope maps changed files to the component.
type Component struct {
	Id *string `json:"id,omitempty"`
	ProductId *string `json:"productId,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	BranchId *string `json:"branchId,omitempty"`
	SourceId *string `json:"sourceId,omitempty"`
	BranchStatus *string `json:"branchStatus,omitempty"`
	// Repository-aware component scope.  canonical repo id (e.g. \"github.com/acme/backend\"); unset = unscoped/main repo
	Repository *string `json:"repository,omitempty"`
	ComponentPaths []string `json:"componentPaths,omitempty"`
	RepositoryAliases []string `json:"repositoryAliases,omitempty"`
}

// NewComponent instantiates a new Component object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComponent() *Component {
	this := Component{}
	return &this
}

// NewComponentWithDefaults instantiates a new Component object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComponentWithDefaults() *Component {
	this := Component{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Component) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Component) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Component) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Component) SetId(v string) {
	o.Id = &v
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *Component) GetProductId() string {
	if o == nil || IsNil(o.ProductId) {
		var ret string
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Component) GetProductIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProductId) {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *Component) HasProductId() bool {
	if o != nil && !IsNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *Component) SetProductId(v string) {
	o.ProductId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Component) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Component) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Component) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Component) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Component) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Component) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Component) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Component) SetDescription(v string) {
	o.Description = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Component) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Component) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Component) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Component) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Component) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Component) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Component) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Component) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetBranchId returns the BranchId field value if set, zero value otherwise.
func (o *Component) GetBranchId() string {
	if o == nil || IsNil(o.BranchId) {
		var ret string
		return ret
	}
	return *o.BranchId
}

// GetBranchIdOk returns a tuple with the BranchId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Component) GetBranchIdOk() (*string, bool) {
	if o == nil || IsNil(o.BranchId) {
		return nil, false
	}
	return o.BranchId, true
}

// HasBranchId returns a boolean if a field has been set.
func (o *Component) HasBranchId() bool {
	if o != nil && !IsNil(o.BranchId) {
		return true
	}

	return false
}

// SetBranchId gets a reference to the given string and assigns it to the BranchId field.
func (o *Component) SetBranchId(v string) {
	o.BranchId = &v
}

// GetSourceId returns the SourceId field value if set, zero value otherwise.
func (o *Component) GetSourceId() string {
	if o == nil || IsNil(o.SourceId) {
		var ret string
		return ret
	}
	return *o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Component) GetSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceId) {
		return nil, false
	}
	return o.SourceId, true
}

// HasSourceId returns a boolean if a field has been set.
func (o *Component) HasSourceId() bool {
	if o != nil && !IsNil(o.SourceId) {
		return true
	}

	return false
}

// SetSourceId gets a reference to the given string and assigns it to the SourceId field.
func (o *Component) SetSourceId(v string) {
	o.SourceId = &v
}

// GetBranchStatus returns the BranchStatus field value if set, zero value otherwise.
func (o *Component) GetBranchStatus() string {
	if o == nil || IsNil(o.BranchStatus) {
		var ret string
		return ret
	}
	return *o.BranchStatus
}

// GetBranchStatusOk returns a tuple with the BranchStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Component) GetBranchStatusOk() (*string, bool) {
	if o == nil || IsNil(o.BranchStatus) {
		return nil, false
	}
	return o.BranchStatus, true
}

// HasBranchStatus returns a boolean if a field has been set.
func (o *Component) HasBranchStatus() bool {
	if o != nil && !IsNil(o.BranchStatus) {
		return true
	}

	return false
}

// SetBranchStatus gets a reference to the given string and assigns it to the BranchStatus field.
func (o *Component) SetBranchStatus(v string) {
	o.BranchStatus = &v
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *Component) GetRepository() string {
	if o == nil || IsNil(o.Repository) {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Component) GetRepositoryOk() (*string, bool) {
	if o == nil || IsNil(o.Repository) {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *Component) HasRepository() bool {
	if o != nil && !IsNil(o.Repository) {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *Component) SetRepository(v string) {
	o.Repository = &v
}

// GetComponentPaths returns the ComponentPaths field value if set, zero value otherwise.
func (o *Component) GetComponentPaths() []string {
	if o == nil || IsNil(o.ComponentPaths) {
		var ret []string
		return ret
	}
	return o.ComponentPaths
}

// GetComponentPathsOk returns a tuple with the ComponentPaths field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Component) GetComponentPathsOk() ([]string, bool) {
	if o == nil || IsNil(o.ComponentPaths) {
		return nil, false
	}
	return o.ComponentPaths, true
}

// HasComponentPaths returns a boolean if a field has been set.
func (o *Component) HasComponentPaths() bool {
	if o != nil && !IsNil(o.ComponentPaths) {
		return true
	}

	return false
}

// SetComponentPaths gets a reference to the given []string and assigns it to the ComponentPaths field.
func (o *Component) SetComponentPaths(v []string) {
	o.ComponentPaths = v
}

// GetRepositoryAliases returns the RepositoryAliases field value if set, zero value otherwise.
func (o *Component) GetRepositoryAliases() []string {
	if o == nil || IsNil(o.RepositoryAliases) {
		var ret []string
		return ret
	}
	return o.RepositoryAliases
}

// GetRepositoryAliasesOk returns a tuple with the RepositoryAliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Component) GetRepositoryAliasesOk() ([]string, bool) {
	if o == nil || IsNil(o.RepositoryAliases) {
		return nil, false
	}
	return o.RepositoryAliases, true
}

// HasRepositoryAliases returns a boolean if a field has been set.
func (o *Component) HasRepositoryAliases() bool {
	if o != nil && !IsNil(o.RepositoryAliases) {
		return true
	}

	return false
}

// SetRepositoryAliases gets a reference to the given []string and assigns it to the RepositoryAliases field.
func (o *Component) SetRepositoryAliases(v []string) {
	o.RepositoryAliases = v
}

func (o Component) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Component) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ProductId) {
		toSerialize["productId"] = o.ProductId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.BranchId) {
		toSerialize["branchId"] = o.BranchId
	}
	if !IsNil(o.SourceId) {
		toSerialize["sourceId"] = o.SourceId
	}
	if !IsNil(o.BranchStatus) {
		toSerialize["branchStatus"] = o.BranchStatus
	}
	if !IsNil(o.Repository) {
		toSerialize["repository"] = o.Repository
	}
	if !IsNil(o.ComponentPaths) {
		toSerialize["componentPaths"] = o.ComponentPaths
	}
	if !IsNil(o.RepositoryAliases) {
		toSerialize["repositoryAliases"] = o.RepositoryAliases
	}
	return toSerialize, nil
}

type NullableComponent struct {
	value *Component
	isSet bool
}

func (v NullableComponent) Get() *Component {
	return v.value
}

func (v *NullableComponent) Set(val *Component) {
	v.value = val
	v.isSet = true
}

func (v NullableComponent) IsSet() bool {
	return v.isSet
}

func (v *NullableComponent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponent(val *Component) *NullableComponent {
	return &NullableComponent{value: val, isSet: true}
}

func (v NullableComponent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


