/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the VerifyProductSetupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyProductSetupResponse{}

// VerifyProductSetupResponse struct for VerifyProductSetupResponse
type VerifyProductSetupResponse struct {
	Setup *ProductSetupState `json:"setup,omitempty"`
}

// NewVerifyProductSetupResponse instantiates a new VerifyProductSetupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyProductSetupResponse() *VerifyProductSetupResponse {
	this := VerifyProductSetupResponse{}
	return &this
}

// NewVerifyProductSetupResponseWithDefaults instantiates a new VerifyProductSetupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyProductSetupResponseWithDefaults() *VerifyProductSetupResponse {
	this := VerifyProductSetupResponse{}
	return &this
}

// GetSetup returns the Setup field value if set, zero value otherwise.
func (o *VerifyProductSetupResponse) GetSetup() ProductSetupState {
	if o == nil || IsNil(o.Setup) {
		var ret ProductSetupState
		return ret
	}
	return *o.Setup
}

// GetSetupOk returns a tuple with the Setup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyProductSetupResponse) GetSetupOk() (*ProductSetupState, bool) {
	if o == nil || IsNil(o.Setup) {
		return nil, false
	}
	return o.Setup, true
}

// HasSetup returns a boolean if a field has been set.
func (o *VerifyProductSetupResponse) HasSetup() bool {
	if o != nil && !IsNil(o.Setup) {
		return true
	}

	return false
}

// SetSetup gets a reference to the given ProductSetupState and assigns it to the Setup field.
func (o *VerifyProductSetupResponse) SetSetup(v ProductSetupState) {
	o.Setup = &v
}

func (o VerifyProductSetupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyProductSetupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Setup) {
		toSerialize["setup"] = o.Setup
	}
	return toSerialize, nil
}

type NullableVerifyProductSetupResponse struct {
	value *VerifyProductSetupResponse
	isSet bool
}

func (v NullableVerifyProductSetupResponse) Get() *VerifyProductSetupResponse {
	return v.value
}

func (v *NullableVerifyProductSetupResponse) Set(val *VerifyProductSetupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyProductSetupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyProductSetupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyProductSetupResponse(val *VerifyProductSetupResponse) *NullableVerifyProductSetupResponse {
	return &NullableVerifyProductSetupResponse{value: val, isSet: true}
}

func (v NullableVerifyProductSetupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyProductSetupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


