/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the ListIssuesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListIssuesResponse{}

// ListIssuesResponse struct for ListIssuesResponse
type ListIssuesResponse struct {
	Issues []Issue `json:"issues,omitempty"`
	Pagination *PaginationResponse `json:"pagination,omitempty"`
	// true when ungrouped events exist for this product (worker hasn't caught up); drives the \"Receiving events, grouping…\" banner.
	Processing *bool `json:"processing,omitempty"`
}

// NewListIssuesResponse instantiates a new ListIssuesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListIssuesResponse() *ListIssuesResponse {
	this := ListIssuesResponse{}
	return &this
}

// NewListIssuesResponseWithDefaults instantiates a new ListIssuesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListIssuesResponseWithDefaults() *ListIssuesResponse {
	this := ListIssuesResponse{}
	return &this
}

// GetIssues returns the Issues field value if set, zero value otherwise.
func (o *ListIssuesResponse) GetIssues() []Issue {
	if o == nil || IsNil(o.Issues) {
		var ret []Issue
		return ret
	}
	return o.Issues
}

// GetIssuesOk returns a tuple with the Issues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListIssuesResponse) GetIssuesOk() ([]Issue, bool) {
	if o == nil || IsNil(o.Issues) {
		return nil, false
	}
	return o.Issues, true
}

// HasIssues returns a boolean if a field has been set.
func (o *ListIssuesResponse) HasIssues() bool {
	if o != nil && !IsNil(o.Issues) {
		return true
	}

	return false
}

// SetIssues gets a reference to the given []Issue and assigns it to the Issues field.
func (o *ListIssuesResponse) SetIssues(v []Issue) {
	o.Issues = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ListIssuesResponse) GetPagination() PaginationResponse {
	if o == nil || IsNil(o.Pagination) {
		var ret PaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListIssuesResponse) GetPaginationOk() (*PaginationResponse, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ListIssuesResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given PaginationResponse and assigns it to the Pagination field.
func (o *ListIssuesResponse) SetPagination(v PaginationResponse) {
	o.Pagination = &v
}

// GetProcessing returns the Processing field value if set, zero value otherwise.
func (o *ListIssuesResponse) GetProcessing() bool {
	if o == nil || IsNil(o.Processing) {
		var ret bool
		return ret
	}
	return *o.Processing
}

// GetProcessingOk returns a tuple with the Processing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListIssuesResponse) GetProcessingOk() (*bool, bool) {
	if o == nil || IsNil(o.Processing) {
		return nil, false
	}
	return o.Processing, true
}

// HasProcessing returns a boolean if a field has been set.
func (o *ListIssuesResponse) HasProcessing() bool {
	if o != nil && !IsNil(o.Processing) {
		return true
	}

	return false
}

// SetProcessing gets a reference to the given bool and assigns it to the Processing field.
func (o *ListIssuesResponse) SetProcessing(v bool) {
	o.Processing = &v
}

func (o ListIssuesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListIssuesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Issues) {
		toSerialize["issues"] = o.Issues
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	if !IsNil(o.Processing) {
		toSerialize["processing"] = o.Processing
	}
	return toSerialize, nil
}

type NullableListIssuesResponse struct {
	value *ListIssuesResponse
	isSet bool
}

func (v NullableListIssuesResponse) Get() *ListIssuesResponse {
	return v.value
}

func (v *NullableListIssuesResponse) Set(val *ListIssuesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListIssuesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListIssuesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListIssuesResponse(val *ListIssuesResponse) *NullableListIssuesResponse {
	return &NullableListIssuesResponse{value: val, isSet: true}
}

func (v NullableListIssuesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListIssuesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


