/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the ChangedFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangedFile{}

// ChangedFile ChangedFile is one repo-qualified changed path.
type ChangedFile struct {
	// repository is the canonical repo id OR a local checkout alias (resolved via component repository_aliases).
	Repository *string `json:"repository,omitempty"`
	// path is repo-relative.
	Path *string `json:"path,omitempty"`
	// status is \"modified\"|\"added\"|\"deleted\" (informational — deleted files are still attributed to their component; the caller decides not to anchor them).
	Status *string `json:"status,omitempty"`
}

// NewChangedFile instantiates a new ChangedFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangedFile() *ChangedFile {
	this := ChangedFile{}
	return &this
}

// NewChangedFileWithDefaults instantiates a new ChangedFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangedFileWithDefaults() *ChangedFile {
	this := ChangedFile{}
	return &this
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *ChangedFile) GetRepository() string {
	if o == nil || IsNil(o.Repository) {
		var ret string
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangedFile) GetRepositoryOk() (*string, bool) {
	if o == nil || IsNil(o.Repository) {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *ChangedFile) HasRepository() bool {
	if o != nil && !IsNil(o.Repository) {
		return true
	}

	return false
}

// SetRepository gets a reference to the given string and assigns it to the Repository field.
func (o *ChangedFile) SetRepository(v string) {
	o.Repository = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ChangedFile) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangedFile) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ChangedFile) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ChangedFile) SetPath(v string) {
	o.Path = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ChangedFile) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangedFile) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ChangedFile) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ChangedFile) SetStatus(v string) {
	o.Status = &v
}

func (o ChangedFile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangedFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Repository) {
		toSerialize["repository"] = o.Repository
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableChangedFile struct {
	value *ChangedFile
	isSet bool
}

func (v NullableChangedFile) Get() *ChangedFile {
	return v.value
}

func (v *NullableChangedFile) Set(val *ChangedFile) {
	v.value = val
	v.isSet = true
}

func (v NullableChangedFile) IsSet() bool {
	return v.isSet
}

func (v *NullableChangedFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangedFile(val *ChangedFile) *NullableChangedFile {
	return &NullableChangedFile{value: val, isSet: true}
}

func (v NullableChangedFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangedFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


