/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the MergeIntentSessionState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MergeIntentSessionState{}

// MergeIntentSessionState MergeIntentSessionState is the merge-relevant slice of an intent session record attached to the branch being previewed/merged — see GetMergePreviewResponse.intent_session and MergeBranchRequest's allow_undistilled.
type MergeIntentSessionState struct {
	SessionId *string `json:"sessionId,omitempty"`
	Status *string `json:"status,omitempty"`
	// settled reports whether the session's settlement has been recorded (settlement IS NOT NULL) — NOT whether the session is closed. A closed session with no settlement is exactly the state the merge guard refuses.
	Settled *bool `json:"settled,omitempty"`
}

// NewMergeIntentSessionState instantiates a new MergeIntentSessionState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMergeIntentSessionState() *MergeIntentSessionState {
	this := MergeIntentSessionState{}
	return &this
}

// NewMergeIntentSessionStateWithDefaults instantiates a new MergeIntentSessionState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMergeIntentSessionStateWithDefaults() *MergeIntentSessionState {
	this := MergeIntentSessionState{}
	return &this
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *MergeIntentSessionState) GetSessionId() string {
	if o == nil || IsNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergeIntentSessionState) GetSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *MergeIntentSessionState) HasSessionId() bool {
	if o != nil && !IsNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *MergeIntentSessionState) SetSessionId(v string) {
	o.SessionId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *MergeIntentSessionState) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergeIntentSessionState) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *MergeIntentSessionState) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *MergeIntentSessionState) SetStatus(v string) {
	o.Status = &v
}

// GetSettled returns the Settled field value if set, zero value otherwise.
func (o *MergeIntentSessionState) GetSettled() bool {
	if o == nil || IsNil(o.Settled) {
		var ret bool
		return ret
	}
	return *o.Settled
}

// GetSettledOk returns a tuple with the Settled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergeIntentSessionState) GetSettledOk() (*bool, bool) {
	if o == nil || IsNil(o.Settled) {
		return nil, false
	}
	return o.Settled, true
}

// HasSettled returns a boolean if a field has been set.
func (o *MergeIntentSessionState) HasSettled() bool {
	if o != nil && !IsNil(o.Settled) {
		return true
	}

	return false
}

// SetSettled gets a reference to the given bool and assigns it to the Settled field.
func (o *MergeIntentSessionState) SetSettled(v bool) {
	o.Settled = &v
}

func (o MergeIntentSessionState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MergeIntentSessionState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SessionId) {
		toSerialize["sessionId"] = o.SessionId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Settled) {
		toSerialize["settled"] = o.Settled
	}
	return toSerialize, nil
}

type NullableMergeIntentSessionState struct {
	value *MergeIntentSessionState
	isSet bool
}

func (v NullableMergeIntentSessionState) Get() *MergeIntentSessionState {
	return v.value
}

func (v *NullableMergeIntentSessionState) Set(val *MergeIntentSessionState) {
	v.value = val
	v.isSet = true
}

func (v NullableMergeIntentSessionState) IsSet() bool {
	return v.isSet
}

func (v *NullableMergeIntentSessionState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMergeIntentSessionState(val *MergeIntentSessionState) *NullableMergeIntentSessionState {
	return &NullableMergeIntentSessionState{value: val, isSet: true}
}

func (v NullableMergeIntentSessionState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMergeIntentSessionState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


