/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the AttributeChangedFilesBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttributeChangedFilesBody{}

// AttributeChangedFilesBody AttributeChangedFiles maps a requirement's repo-qualified changed files to components via the MAIN component scope, declares one idempotent impacts_component edge-intent per touched component, and sets/clears requirement.component_id. Enforces the one-repo-per-node invariant: the changed files must belong to a single repository.
type AttributeChangedFilesBody struct {
	// branch the requirement lives on (empty = main).
	Branch *string `json:"branch,omitempty"`
	ChangedFiles []ChangedFile `json:"changedFiles,omitempty"`
}

// NewAttributeChangedFilesBody instantiates a new AttributeChangedFilesBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttributeChangedFilesBody() *AttributeChangedFilesBody {
	this := AttributeChangedFilesBody{}
	return &this
}

// NewAttributeChangedFilesBodyWithDefaults instantiates a new AttributeChangedFilesBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttributeChangedFilesBodyWithDefaults() *AttributeChangedFilesBody {
	this := AttributeChangedFilesBody{}
	return &this
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *AttributeChangedFilesBody) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributeChangedFilesBody) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *AttributeChangedFilesBody) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *AttributeChangedFilesBody) SetBranch(v string) {
	o.Branch = &v
}

// GetChangedFiles returns the ChangedFiles field value if set, zero value otherwise.
func (o *AttributeChangedFilesBody) GetChangedFiles() []ChangedFile {
	if o == nil || IsNil(o.ChangedFiles) {
		var ret []ChangedFile
		return ret
	}
	return o.ChangedFiles
}

// GetChangedFilesOk returns a tuple with the ChangedFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AttributeChangedFilesBody) GetChangedFilesOk() ([]ChangedFile, bool) {
	if o == nil || IsNil(o.ChangedFiles) {
		return nil, false
	}
	return o.ChangedFiles, true
}

// HasChangedFiles returns a boolean if a field has been set.
func (o *AttributeChangedFilesBody) HasChangedFiles() bool {
	if o != nil && !IsNil(o.ChangedFiles) {
		return true
	}

	return false
}

// SetChangedFiles gets a reference to the given []ChangedFile and assigns it to the ChangedFiles field.
func (o *AttributeChangedFilesBody) SetChangedFiles(v []ChangedFile) {
	o.ChangedFiles = v
}

func (o AttributeChangedFilesBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttributeChangedFilesBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.ChangedFiles) {
		toSerialize["changedFiles"] = o.ChangedFiles
	}
	return toSerialize, nil
}

type NullableAttributeChangedFilesBody struct {
	value *AttributeChangedFilesBody
	isSet bool
}

func (v NullableAttributeChangedFilesBody) Get() *AttributeChangedFilesBody {
	return v.value
}

func (v *NullableAttributeChangedFilesBody) Set(val *AttributeChangedFilesBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAttributeChangedFilesBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAttributeChangedFilesBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttributeChangedFilesBody(val *AttributeChangedFilesBody) *NullableAttributeChangedFilesBody {
	return &NullableAttributeChangedFilesBody{value: val, isSet: true}
}

func (v NullableAttributeChangedFilesBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttributeChangedFilesBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


