/*
Tiden Public API

REST API for external consumers: the tiden CLI, reporters, and generated API clients. Authenticate with an API token (`Authorization: Bearer tfy_...`) created in the app UI or via the CLI device-code flow.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tidenapi

import (
	"encoding/json"
)

// checks if the GetTestResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTestResponse{}

// GetTestResponse struct for GetTestResponse
type GetTestResponse struct {
	Test *Test `json:"test,omitempty"`
}

// NewGetTestResponse instantiates a new GetTestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTestResponse() *GetTestResponse {
	this := GetTestResponse{}
	return &this
}

// NewGetTestResponseWithDefaults instantiates a new GetTestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTestResponseWithDefaults() *GetTestResponse {
	this := GetTestResponse{}
	return &this
}

// GetTest returns the Test field value if set, zero value otherwise.
func (o *GetTestResponse) GetTest() Test {
	if o == nil || IsNil(o.Test) {
		var ret Test
		return ret
	}
	return *o.Test
}

// GetTestOk returns a tuple with the Test field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTestResponse) GetTestOk() (*Test, bool) {
	if o == nil || IsNil(o.Test) {
		return nil, false
	}
	return o.Test, true
}

// HasTest returns a boolean if a field has been set.
func (o *GetTestResponse) HasTest() bool {
	if o != nil && !IsNil(o.Test) {
		return true
	}

	return false
}

// SetTest gets a reference to the given Test and assigns it to the Test field.
func (o *GetTestResponse) SetTest(v Test) {
	o.Test = &v
}

func (o GetTestResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTestResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Test) {
		toSerialize["test"] = o.Test
	}
	return toSerialize, nil
}

type NullableGetTestResponse struct {
	value *GetTestResponse
	isSet bool
}

func (v NullableGetTestResponse) Get() *GetTestResponse {
	return v.value
}

func (v *NullableGetTestResponse) Set(val *GetTestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTestResponse(val *GetTestResponse) *NullableGetTestResponse {
	return &NullableGetTestResponse{value: val, isSet: true}
}

func (v NullableGetTestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


